/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.BD.Conecta_Banco;
import Model.VO.Cadastro_FuncionarioVO;
import View.Complementares.JI_Cargo;
import View.Complementares.JI_Cargo;
import View.Complementares.JI_Formacao;
import View.Complementares.JI_Setor;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class Frm_Principal extends javax.swing.JFrame {

    Cadastro_FuncionarioVO ModFuncionario = new Cadastro_FuncionarioVO();
    
    Conecta_Banco Conexao = new Conecta_Banco();
    
   
    
    /**
     * Creates new form Frm_Principal
     */
    public Frm_Principal(String User) {
        initComponents();
   
        setExtendedState(MAXIMIZED_BOTH);
        
       jLabelUser.setText(User);
        
       ModFuncionario.setLogin_Funcionario(User);
    
       //Envia_User = new JI_Estoque();
       //Envia_User.User(jLabelUser.getText());
       
       ModFuncionario.setNome_Funcionario(jLabelUser.getText());
   
    }

    Frm_Principal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jLabelUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Principal");

        jDesktopPanePrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPanePrincipal.setRequestFocusEnabled(false);

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setText("jLabelUser");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem Vindo!");

        jDesktopPanePrincipal.setLayer(jLabelUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelUser)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Cadastro");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem22.setText("Login");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Produtos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Fornecedor");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem10.setText("Funcionario");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem3.setText("Cargo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Formação");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem9.setText("Setor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Estoque");

        jMenuItem8.setText("Produtos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vendas");

        jMenuItem13.setText("Produtos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Fluxo de Caixa");

        jMenuItem11.setText("Contas A Pagar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuItem23.setText("Contas A Receber");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenuBar1.add(jMenu8);

        jMenu4.setText("Relatórios");

        jMenuItem2.setText("Estoque");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem7.setText("Vendas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sair");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPanePrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPanePrincipal)
                .addContainerGap())
        );

        setBounds(0, 0, 836, 574);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        
        try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

        JI_VendaPecas Pecas = new JI_VendaPecas(jLabelUser.getText());
        
        jDesktopPanePrincipal.add(Pecas);
        
        Pecas.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

        
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
        try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

    JI_Fornecedor Fornecedor = new JI_Fornecedor();
    
    jDesktopPanePrincipal.add(Fornecedor);
    
    Fornecedor.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();
    
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        
      if(JOptionPane.showConfirmDialog(null, "Confirmar Logoff", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

        
        Frm_LoginInicial Login = new Frm_LoginInicial();
                
        Login.setVisible(true);

        dispose();
        
      }
        
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

    
        JI_Pecas Pecas = new JI_Pecas();
        
        jDesktopPanePrincipal.add(Pecas);
        
        Pecas.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

                
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

    
        JI_Cliente Cliente = new JI_Cliente(jLabelUser.getText());
        
        jDesktopPanePrincipal.add(Cliente);
        
        Cliente.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

               
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Adm_Inicial"))){

JI_LoginCadastro Login = new JI_LoginCadastro();
jDesktopPanePrincipal.add(Login);

Login.setVisible(true);

}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();
        
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

        JI_Estoque Estoque = new JI_Estoque(jLabelUser.getText());
        
        jDesktopPanePrincipal.add(Estoque);
        
        Estoque.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:

try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão") || (Conexao.rs.getString("Permissao").equals("Adm_Inicial")))){

    
      JI_Funcionario Funcionario = new JI_Funcionario();
      
      jDesktopPanePrincipal.add(Funcionario);
      
      Funcionario.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
      
        
        try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão") || (Conexao.rs.getString("Permissao").equals("Adm_Inicial")))){

        JI_Cargo Cargo = new JI_Cargo();
        
        jDesktopPanePrincipal.add(Cargo);
        
        Cargo.setVisible(true);
        
    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão") || (Conexao.rs.getString("Permissao").equals("Adm_Inicial")))){

        JI_Formacao Formacao = new JI_Formacao();
        
        jDesktopPanePrincipal.add(Formacao);
        
        Formacao.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

                
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
       
        try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão") || (Conexao.rs.getString("Permissao").equals("Adm_Inicial")))){

        JI_Setor Setor = new JI_Setor();
        
        jDesktopPanePrincipal.add(Setor);
        
        Setor.setVisible(true);
        
    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão")) || (Conexao.rs.getString("Permissao").equals("Básico")) ){

        RE_Estoque Estoque = new RE_Estoque(jLabelUser.getText());
        
        jDesktopPanePrincipal.add(Estoque);
        
        Estoque.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

               
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

        RE_Vendas RE_Vendas = new RE_Vendas(jLabelUser.getText());
        
        jDesktopPanePrincipal.add(RE_Vendas);
        
        RE_Vendas.setVisible(true);

    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

                
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:

try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

    
        JI_ContasPagar ContasPagar = new JI_ContasPagar(jLabelUser.getText());
        
        jDesktopPanePrincipal.add(ContasPagar);
        
        ContasPagar.setVisible(true);
    
    

}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

        
        
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
       
        try {
    Conexao.conexao();
Conexao.executaSQL("select * from login where Nome_acesso ='"+jLabelUser.getText()+"'");
Conexao.rs.first();
if(Conexao.rs.getString("Permissao").equals("Administrador") || (Conexao.rs.getString("Permissao").equals("Padrão"))){

    JI_ContasReceber ContasReceber = new JI_ContasReceber();
        
        jDesktopPanePrincipal.add(ContasReceber);
        
        ContasReceber.setVisible(true);
        
    
}else
        JOptionPane.showMessageDialog(null, "Login Não Tem Permissão de Acesso");
     
        
}catch (SQLException ex){
                
                
                
                }
Conexao.desconecta();

        
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_jMenu5ActionPerformed

    
        public void User_Dados (){
        ModFuncionario.setNome_Funcionario(jLabelUser.getText());
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
