/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.Complementares.Frm_AdicionarContasMenu;
import View.Complementares.*;
import View.*;
import Model.BD.Conecta_Banco;
import Model.BO.Contas_PagarBO;
import Model.DAO.ContasPagarDAO;
import Model.DAO.FuncionarioDAO;
import Model.VO.Cadastro_FuncionarioVO;
import Model.VO.Cadastro_MarcaVO;
import Model.VO.Cadastro_NFVO;
import Model.VO.ContasPagarVO;
import Model.VO.Dados_iniciaisVO;
import Model.VO.Estoque_ProdutosVO;
import Model.VO.Fechamento_CaixaVO;
import Model.VO.ModeloTabela;
import Model.VO.SCadastro_Fornecedores;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import sun.misc.FloatingDecimal;

/**
 *
 * @author Lucas
 */
public class JI_ContasPagar extends javax.swing.JInternalFrame {


    Conecta_Banco Conexao = new Conecta_Banco();
   
   Cadastro_FuncionarioVO ModFuncionario = new Cadastro_FuncionarioVO();
    
    ContasPagarDAO ControlContas = new ContasPagarDAO();
    
    ContasPagarVO ModContas = new ContasPagarVO();
    
    Fechamento_CaixaVO ModFechamento = new Fechamento_CaixaVO();
    
    Contas_PagarBO ContasBO = new Contas_PagarBO();
    
    SCadastro_Fornecedores ModFornecedor = new SCadastro_Fornecedores();
    
        Cadastro_NFVO ModNF = new Cadastro_NFVO();
        Estoque_ProdutosVO ModEstoque = new Estoque_ProdutosVO();

        Float TotalDisponivel_Restante;

 NumberFormat VL_Moeda;
// NumberFormat VL_Float;
 
 Locale localeUS = new Locale("en", "US");
 Locale LocaleBR = new Locale("pt", "BR");         
    /**
     * Creates new form NewJInternalFrame
     */
    public JI_ContasPagar(String NomeUser_Contas) {
        initComponents();

        jTextFieldDisponivelMouseClicked(null);
        
        Preencher_ComboStatus();
        Preencher_ComboFiltro();
        Hora_Atual_Sistema();
       
//         jTextFieldDisponivelDiaMouseClicked(null);
       

         jLabelC_Pagarnome.setText(NomeUser_Contas);
            
         Buscar_Fechamento();
         
         jTextFieldDisponivelDiaMouseClicked(null);

         jButton1.setEnabled(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabelC_Pagarusuario = new javax.swing.JLabel();
        jLabelC_Pagarnome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigoFornecedor = new javax.swing.JTextField();
        jTextFieldNome_Fornecedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCombustivel = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumero_NF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldData_Vencimento = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDisponivelDia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jTextFieldDisponivel = new javax.swing.JFormattedTextField();
        jButtonFechar_Caixa = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jFormattedTextFieldData_Fechamento = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField_Retirada = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField_Reservado = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxStatus_Pagamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxFiltro_Pesquisa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTotal_Pagamento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonAddContas = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Contas a Pagar");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Executar Pesquisa");
        jButtonPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SUPERMERCADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Logout_Icon_48.png"))); // NOI18N
        jButtonSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelC_Pagarusuario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelC_Pagarusuario.setForeground(java.awt.Color.blue);
        jLabelC_Pagarusuario.setText("Usuario Logado");

        jLabelC_Pagarnome.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelC_Pagarnome.setForeground(java.awt.Color.blue);
        jLabelC_Pagarnome.setText("Nome Usuário");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelC_Pagarusuario)
                    .addComponent(jLabelC_Pagarnome))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelC_Pagarusuario)
                .addGap(3, 3, 3)
                .addComponent(jLabelC_Pagarnome))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Cód. Fornecedor");

        jLabel3.setText("Fornecedor");

        jTableCombustivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCombustivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCombustivelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCombustivel);

        jLabel4.setText("Número da NF");

        jLabel5.setText("Vencimento Maior Que");

        try {
            jFormattedTextFieldData_Vencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Total Geral");

        jTextFieldDisponivelDia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldDisponivelDia.setForeground(java.awt.Color.blue);
        jTextFieldDisponivelDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDisponivelDiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldDisponivelDiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldDisponivelDiaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldDisponivelDiaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldDisponivelDiaMouseReleased(evt);
            }
        });
        jTextFieldDisponivelDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDisponivelDiaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDisponivelDiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDisponivelDiaKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(java.awt.Color.blue);
        jLabel13.setText("Total Caixa/Dia");

        jFormattedTextFieldData.setEditable(false);
        jFormattedTextFieldData.setForeground(java.awt.Color.blue);

        jTextFieldDisponivel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldDisponivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDisponivelMouseClicked(evt);
            }
        });

        jButtonFechar_Caixa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFechar_Caixa.setForeground(java.awt.Color.blue);
        jButtonFechar_Caixa.setText("Fechar Caixa");
        jButtonFechar_Caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechar_CaixaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(java.awt.Color.blue);
        jLabel14.setText("Total Retirada");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Data");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fechamento Anterior");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldData_Fechamento)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldData_Fechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jFormattedTextField_Retirada.setText("0.00");
        jFormattedTextField_Retirada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField_RetiradaMouseClicked(evt);
            }
        });
        jFormattedTextField_Retirada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_RetiradaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField_RetiradaKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Reservado");

        jFormattedTextField_Reservado.setEditable(false);
        jFormattedTextField_Reservado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextField_Reservado.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonFechar_Caixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldDisponivelDia)
                                .addComponent(jFormattedTextField_Retirada, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(jFormattedTextField_Reservado, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField_Reservado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDisponivelDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jFormattedTextField_Retirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar_Caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fechamento de Caixa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setText("Pagamento da NF");

        jComboBoxStatus_Pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Filtro de Pesquisa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Listagem");

        jComboBoxFiltro_Pesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFiltro_Pesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFiltro_PesquisaItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Total Pagamento");

        jTextFieldTotal_Pagamento.setEditable(false);
        jTextFieldTotal_Pagamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAddContas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddContas.setText("ADD CONTAS");
        jButtonAddContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jTextFieldTotal_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jButtonAddContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxStatus_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNumero_NF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldData_Vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldNome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxFiltro_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFiltro_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jComboBoxStatus_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddContas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNumero_NF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextFieldData_Vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTotal_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        setBounds(0, 0, 870, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:

        
        
if(jComboBoxStatus_Pagamento.getSelectedItem().equals("-Sel-") && jTextFieldCodigoFornecedor.getText().equals("") 
        && jTextFieldNome_Fornecedor.getText().equals("") && jTextFieldNumero_NF.getText().equals("") && jFormattedTextFieldData_Vencimento.getText().equals("  -  -    ") ) {
        
//        PreencherTabela_Cargo("SELECT * FROM estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` inner join nota_fiscal on pecas.`idPecas` = nota_fiscal.`Pecas_idPecas` inner join fornecedor on nota_fiscal.fornecedor_idfornecedor = fornecedor.idfornecedor order by nota_fiscal.`Data_vencimento`");
        
        PreencherTabela_Cargo("select * from nota_fiscal inner join fornecedor on fornecedor.idfornecedor = nota_fiscal.fornecedor_idfornecedor");
        
        
    }else{
    
    String Pagamento = (String) jComboBoxStatus_Pagamento.getSelectedItem();
if(Pagamento != "-Sel-"  && jTextFieldCodigoFornecedor.getText().equals("") 
        && jTextFieldNome_Fornecedor.getText().equals("") && jTextFieldNumero_NF.getText().equals("") && jFormattedTextFieldData_Vencimento.getText().equals("  -  -    ")) {

    PreencherTabela_Cargo("SELECT * FROM nota_fiscal inner join pecas on nota_fiscal.`Pecas_idPecas` = pecas.`idPecas` inner join fornecedor on nota_fiscal.fornecedor_idfornecedor = fornecedor.idfornecedor where nota_fiscal.`Pagamento`='"+jComboBoxStatus_Pagamento.getSelectedItem()+"'");
    
    }else{
    
        String Fornecedor = jTextFieldCodigoFornecedor.getText();
if(jComboBoxStatus_Pagamento.getSelectedItem().equals("-Sel-") && Fornecedor != "" 
        && jTextFieldNome_Fornecedor.getText().equals("") && jTextFieldNumero_NF.getText().equals("") && jFormattedTextFieldData_Vencimento.getText().equals("  -  -    ")) {

    PreencherTabela_Cargo("SELECT * FROM nota_fiscal inner join pecas on nota_fiscal.`Pecas_idPecas` = pecas.`idPecas` inner join fornecedor on nota_fiscal.fornecedor_idfornecedor = fornecedor.idfornecedor where fornecedor.idfornecedor ='"+jTextFieldCodigoFornecedor.getText()+"'");
    
    
}else{
    
    String NomeFornecedor = jTextFieldNome_Fornecedor.getText();
if(jComboBoxStatus_Pagamento.getSelectedItem().equals("-Sel-") && jTextFieldCodigoFornecedor.getText().equals("") 
        && NomeFornecedor != "" && jTextFieldNumero_NF.getText().equals("") && jFormattedTextFieldData_Vencimento.getText().equals("  -  -    ")) {
 
    PreencherTabela_Cargo("SELECT * FROM nota_fiscal inner join pecas on nota_fiscal.`Pecas_idPecas` = pecas.`idPecas` inner join fornecedor on nota_fiscal.fornecedor_idfornecedor = fornecedor.idfornecedor WHERE fornecedor.nome_fornecedor like '%"+jTextFieldNome_Fornecedor.getText()+"%'");
    
    
}else{
    
    String Numero_NF = jTextFieldNumero_NF.getText();
if(jComboBoxStatus_Pagamento.getSelectedItem().equals("-Sel-") && jTextFieldCodigoFornecedor.getText().equals("") && jFormattedTextFieldData_Vencimento.getText().equals("  -  -    ") 
        && NomeFornecedor != "" && Numero_NF != "") {
 
    PreencherTabela_Cargo("SELECT * FROM nota_fiscal inner join pecas on nota_fiscal.`Pecas_idPecas` = pecas.`idPecas` inner join fornecedor on nota_fiscal.fornecedor_idfornecedor = fornecedor.idfornecedor WHERE nota_fiscal.`Numero_NF` ='"+jTextFieldNumero_NF.getText()+"'");
 
}else{
    String Data_Final_String = jFormattedTextFieldData_Vencimento.getText();
if(jComboBoxStatus_Pagamento.getSelectedItem().equals("-Sel-") && jTextFieldCodigoFornecedor.getText().equals("") 
        && jTextFieldNome_Fornecedor.getText().equals("") && jTextFieldNumero_NF.getText().equals("") && Data_Final_String != "  -  -    ") {
 
            //Data Validade Inicial
        String diava = jFormattedTextFieldData_Vencimento.getText().substring(0,2);
        String mesva = jFormattedTextFieldData_Vencimento.getText().substring(3,5);
        String anova = jFormattedTextFieldData_Vencimento.getText().substring(6);
        String D_VI = (anova+"-"+mesva+"-"+diava);

    
        PreencherTabela_Cargo("SELECT * FROM nota_fiscal inner join pecas on nota_fiscal.`Pecas_idPecas` = pecas.`idPecas` inner join fornecedor on nota_fiscal.fornecedor_idfornecedor = fornecedor.idfornecedor where nota_fiscal.`Data_vencimento` >'"+D_VI+"'");
     
    }
}
}    
}
}
}
    
//SELECT * FROM estoque inner join fornecedor on estoque.fornecedor_idfornecedor = fornecedor.idfornecedor inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` inner join nota_fiscal on pecas.`idPecas` = nota_fiscal.`Pecas_idPecas` where nota_fiscal.`Data_vencimento` >"2016-10-31"

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:

        dispose();
        

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

            if(JOptionPane.showConfirmDialog(null, "Confirmar pagamento de conta?", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

        
                ModContas.setNumero_NF_Contas(Integer.parseInt(jTextFieldNumero_NF.getText()));
                ModContas.setCod_Fornecedor(Integer.parseInt(jTextFieldCodigoFornecedor.getText()));
                
                ModContas.setTotal_Pagamento(Float.parseFloat(jTextFieldTotal_Pagamento.getText()));    
                ModContas.setTotal_disponivel(Float.parseFloat(jTextFieldDisponivel.getText()));
                
                ModContas.setSituacao_Pagamento("Pago");
                
                //Data Para Sql
                String dia = jFormattedTextFieldData.getText().substring(0,2);
                String mes = jFormattedTextFieldData.getText().substring(3,5);
                String ano = jFormattedTextFieldData.getText().substring(6,10);
                String hora = jFormattedTextFieldData.getText().substring(11,13);
                String minuto = jFormattedTextFieldData.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);

                //Calcular Valor Disponivel Restante
                Calcular_Disponivel();
                
                ModContas.setValor_Disponivel(TotalDisponivel_Restante);
                
                Consultar_ID_VL();
                
//                ControlContas.Atualizar_SituacaoPagamento(ModContas);
                ContasBO.Pagar_Conta(ModContas);
                
                jTextFieldDisponivelMouseClicked(null);
                jButtonPesquisarActionPerformed(null);

                
            }
                
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxFiltro_PesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFiltro_PesquisaItemStateChanged
        // TODO add your handling code here:
        
        String Combo_Item = (String) jComboBoxFiltro_Pesquisa.getSelectedItem();
        
        if(Combo_Item == "-Sel-"){
            
            //Protege os Campos
            jTextFieldCodigoFornecedor.setEnabled(false);
            jTextFieldNome_Fornecedor.setEnabled(false);
            jTextFieldNumero_NF.setEnabled(false);
            jFormattedTextFieldData_Vencimento.setEnabled(false);
            jComboBoxStatus_Pagamento.setEnabled(false);
            
            //Limpar Campos
            jTextFieldCodigoFornecedor.setText("");
            jTextFieldNome_Fornecedor.setText("");
            jTextFieldNumero_NF.setText("");
            jFormattedTextFieldData_Vencimento.setText("");
            Preencher_ComboStatus();
            
        }else{
            
            if(Combo_Item == "Situação do Pagamento"){
  
            //Protege os Campos
            jTextFieldCodigoFornecedor.setEnabled(false);
            jTextFieldNome_Fornecedor.setEnabled(false);
            jTextFieldNumero_NF.setEnabled(false);
            jFormattedTextFieldData_Vencimento.setEnabled(false);
            jComboBoxStatus_Pagamento.setEnabled(true);
            
            //Limpar Campos
            jTextFieldCodigoFornecedor.setText("");
            jTextFieldNome_Fornecedor.setText("");
            jTextFieldNumero_NF.setText("");
            jFormattedTextFieldData_Vencimento.setText("");
            Preencher_ComboStatus();
  
                
            }else{
                
                if(Combo_Item == "Código Fornecedor"){
                    
                    //Protege os Campos
            jTextFieldCodigoFornecedor.setEnabled(true);
            jTextFieldNome_Fornecedor.setEnabled(false);
            jTextFieldNumero_NF.setEnabled(false);
            jFormattedTextFieldData_Vencimento.setEnabled(false);
            jComboBoxStatus_Pagamento.setEnabled(false);
            
            //Limpar Campos
            jTextFieldCodigoFornecedor.setText("");
            jTextFieldNome_Fornecedor.setText("");
            jTextFieldNumero_NF.setText("");
            jFormattedTextFieldData_Vencimento.setText("");
            Preencher_ComboStatus();
                    
                }else{
                    
                    if(Combo_Item == "Nome Fornecedor"){
                        
                        //Protege os Campos
            jTextFieldCodigoFornecedor.setEnabled(false);
            jTextFieldNome_Fornecedor.setEnabled(true);
            jTextFieldNumero_NF.setEnabled(false);
            jFormattedTextFieldData_Vencimento.setEnabled(false);
            jComboBoxStatus_Pagamento.setEnabled(false);
            
            //Limpar Campos
            jTextFieldCodigoFornecedor.setText("");
            jTextFieldNome_Fornecedor.setText("");
            jTextFieldNumero_NF.setText("");
            jFormattedTextFieldData_Vencimento.setText("");
            Preencher_ComboStatus();
                        
                    }else{
                        
                        if(Combo_Item == "Número da NF"){
                            
            //Protege os Campos
            jTextFieldCodigoFornecedor.setEnabled(false);
            jTextFieldNome_Fornecedor.setEnabled(false);
            jTextFieldNumero_NF.setEnabled(true);
            jFormattedTextFieldData_Vencimento.setEnabled(false);
            jComboBoxStatus_Pagamento.setEnabled(false);
            
            //Limpar Campos
            jTextFieldCodigoFornecedor.setText("");
            jTextFieldNome_Fornecedor.setText("");
            jTextFieldNumero_NF.setText("");
            jFormattedTextFieldData_Vencimento.setText("");
            Preencher_ComboStatus();

                            
                        }else{
                            
                            if(Combo_Item == "Data de Vencimento"){
                            
             //Protege os Campos
            jTextFieldCodigoFornecedor.setEnabled(false);
            jTextFieldNome_Fornecedor.setEnabled(false);
            jTextFieldNumero_NF.setEnabled(false);
            jFormattedTextFieldData_Vencimento.setEnabled(true);
            jComboBoxStatus_Pagamento.setEnabled(false);
            
            //Limpar Campos
            jTextFieldCodigoFornecedor.setText("");
            jTextFieldNome_Fornecedor.setText("");
            jTextFieldNumero_NF.setText("");
            jFormattedTextFieldData_Vencimento.setText("");
            Preencher_ComboStatus();

                                
                            }
                            
                        }
                        
                    }
                    
                }
                
            }
            
        }

       
    }//GEN-LAST:event_jComboBoxFiltro_PesquisaItemStateChanged

    private void jTableCombustivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCombustivelMouseClicked
        // TODO add your handling code here:
        
        Valores_TabelaPesquisa();
        
       // jButtonProximoActionPerformed(null);

       Conexao.conexao();
       
       Conexao.executaSQL("select * from nota_fiscal WHERE nota_fiscal.`Numero_NF` ='"+jTextFieldNumero_NF.getText()+"' and nota_fiscal.fornecedor_idfornecedor ='"+jTextFieldCodigoFornecedor.getText()+"'");
        try {
            
            Conexao.rs.first();
           
            
            if(Conexao.rs.getString("Pagamento").equals("Em Aberto")){
                 
                jButton1.setEnabled(true);
                
            }else{
                
                if(Conexao.rs.getString("Pagamento").equals("Pago")){
                    
                    jButton1.setEnabled(false);
                    
                }
                
            }
        
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro ao selecionar conta!");
        
        }
       
       
    }//GEN-LAST:event_jTableCombustivelMouseClicked

    private void jTextFieldDisponivelDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaMouseClicked
        // TODO add your handling code here:

        jTextFieldDisponivelMouseClicked(null);
        
        try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(evt);
        }
       
    }//GEN-LAST:event_jTextFieldDisponivelDiaMouseClicked

    private void jTextFieldDisponivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelMouseClicked
        // TODO add your handling code here:

try{

    
        ControlContas.Valor_Dsponivel(ModContas);
        ControlContas.Valor_DsponivelPrazo(ModContas);
        ControlContas.Valor_Pagamentos(ModContas);
        
      //Float Res_TotalDisponivel = (ModContas.getValor_Disponivel() + ModContas.getValor_Disponivel2());
        Float Res_TotalDisponivel = (ModContas.getValor_Disponivel() + ModContas.getValor_Disponivel2() - ModContas.getValor_Disponivel3());
        
        
       //Formatar
//       VL_Moeda = NumberFormat.getInstance();
//       VL_Moeda.setMaximumFractionDigits(2);       
       
       NumberFormat DinheiroUS = NumberFormat.getNumberInstance(localeUS);
       DinheiroUS.setMaximumFractionDigits(2);
       NumberFormat DinheiroBR = NumberFormat.getNumberInstance(LocaleBR);
       DinheiroBR.setMaximumFractionDigits(2);
       
//       jTextFieldDisponivel.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivel)));

        jTextFieldDisponivel.setText(String.valueOf(DinheiroUS.format(Res_TotalDisponivel)));
       
}catch(NumberFormatException e){
    
    JOptionPane.showMessageDialog(null, "erro");
    
}   
       
    }//GEN-LAST:event_jTextFieldDisponivelMouseClicked

    private void jButtonFechar_CaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechar_CaixaActionPerformed
        // TODO add your handling code here:

        /*
                     //Data Para Sql
                String dia = jFormattedTextFieldData.getText().substring(0,2);
                String mes = jFormattedTextFieldData.getText().substring(3,5);
                String ano = jFormattedTextFieldData.getText().substring(6,10);
                String hora = jFormattedTextFieldData.getText().substring(11,13);
                String minuto = jFormattedTextFieldData.getText().substring(14,16);
                
                String Data_Fechamento = (ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
                ModFechamento.setData_Fechamento(Data_Fechamento);
                ModFechamento.setValor_Fechamento(Float.parseFloat(jTextFieldDisponivelDia.getText()));
                
                ModFechamento.setNome_Usuario(jLabelC_Pagarnome.getText());
                               
                Pesquisar_Usuario();
                
                ModFechamento.setVL_Retirada(Float.parseFloat(jFormattedTextField_Retirada.getText()));
                
                ControlContas.Fechar_Caixa(ModFechamento);
   
                Buscar_Fechamento();
                jTextFieldDisponivelDiaMouseClicked(null);
        
        */
        
        
        float retirada = Float.parseFloat(jFormattedTextField_Retirada.getText());
        
        if(retirada == 0){
        
            JOptionPane.showMessageDialog(null,"Sem Retirada!");
 
            if(JOptionPane.showConfirmDialog(null, "Confirmar Fechamento de Caixa?", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){
            
            
                //Data Para Sql
                String dia = jFormattedTextFieldData.getText().substring(0,2);
                String mes = jFormattedTextFieldData.getText().substring(3,5);
                String ano = jFormattedTextFieldData.getText().substring(6,10);
                String hora = jFormattedTextFieldData.getText().substring(11,13);
                String minuto = jFormattedTextFieldData.getText().substring(14,16);
                
                String Data_Fechamento = (ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
                ModFechamento.setData_Fechamento(Data_Fechamento);
                ModFechamento.setValor_Fechamento(Float.parseFloat(jTextFieldDisponivelDia.getText()));
                ModFechamento.setVL_Retirada(Float.parseFloat(jFormattedTextField_Retirada.getText()));
                ModFechamento.setNome_Usuario(jLabelC_Pagarnome.getText());
                               
                Pesquisar_Usuario();
                
                
                
//                ControlContas.Fechar_Caixa(ModFechamento);
                
                ContasBO.Fechar_Caixa(ModFechamento);
                
                Buscar_Fechamento();
                jTextFieldDisponivelDiaMouseClicked(null);

            }    
                
 }else{
         
            
            if(retirada > 0){
 
                JOptionPane.showMessageDialog(null,"Retirada de "+retirada);
                
                if(JOptionPane.showConfirmDialog(null, "Confirmar Fechamento de Caixa?", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){
        
                
                    //Data Para Sql
                String dia = jFormattedTextFieldData.getText().substring(0,2);
                String mes = jFormattedTextFieldData.getText().substring(3,5);
                String ano = jFormattedTextFieldData.getText().substring(6,10);
                String hora = jFormattedTextFieldData.getText().substring(11,13);
                String minuto = jFormattedTextFieldData.getText().substring(14,16);
                
                String Data_Fechamento = (ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
                ModFechamento.setData_Fechamento(Data_Fechamento);
                ModFechamento.setValor_Fechamento(Float.parseFloat(jTextFieldDisponivelDia.getText()));
                
                ModFechamento.setNome_Usuario(jLabelC_Pagarnome.getText());
                               
                Pesquisar_Usuario();
                
                ModFechamento.setVL_Retirada(Float.parseFloat(jFormattedTextField_Retirada.getText()));
                
//                ControlContas.Fechar_Caixa(ModFechamento);
   
                ContasBO.Fechar_Caixa(ModFechamento);
                
                Buscar_Fechamento();
                jTextFieldDisponivelDiaMouseClicked(null);

                }
                
            }
            
        } 
        
        
                
    }//GEN-LAST:event_jButtonFechar_CaixaActionPerformed

    private void jButtonAddContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContasActionPerformed
        // TODO add your handling code here:
        
        Frm_AdicionarContasMenu Iniciar_AddContas = new Frm_AdicionarContasMenu();
        
        
        Iniciar_AddContas.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonAddContasActionPerformed

    private void jFormattedTextField_RetiradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField_RetiradaMouseClicked
        // TODO add your handling code here:
        
        try{

            float retirada = Float.parseFloat(jFormattedTextField_Retirada.getText());
            
        }catch (NumberFormatException e){
        
        jFormattedTextField_Retirada.setText("0.0");
    }
        
    }//GEN-LAST:event_jFormattedTextField_RetiradaMouseClicked

    private void jTextFieldDisponivelDiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaKeyPressed
        // TODO add your handling code here:
        
        jTextFieldDisponivelMouseClicked(null);
         
                try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(null);
        }

         
        
    }//GEN-LAST:event_jTextFieldDisponivelDiaKeyPressed

    private void jTextFieldDisponivelDiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaKeyReleased
        // TODO add your handling code here:
        
        jTextFieldDisponivelMouseClicked(null);
         
         try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(null);
        }
        
    }//GEN-LAST:event_jTextFieldDisponivelDiaKeyReleased

    private void jTextFieldDisponivelDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaKeyTyped
        // TODO add your handling code here:
        
        jTextFieldDisponivelMouseClicked(null);
         
        try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(null);
        }
        
    }//GEN-LAST:event_jTextFieldDisponivelDiaKeyTyped

    private void jTextFieldDisponivelDiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaMouseReleased
        // TODO add your handling code here:

        jTextFieldDisponivelMouseClicked(null);
        
        try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(null);
        }
        
    }//GEN-LAST:event_jTextFieldDisponivelDiaMouseReleased

    private void jTextFieldDisponivelDiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaMouseEntered
        // TODO add your handling code here:
        
        jTextFieldDisponivelMouseClicked(null);
        
        try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(null);
        }
        
    }//GEN-LAST:event_jTextFieldDisponivelDiaMouseEntered

    private void jTextFieldDisponivelDiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaMouseExited
        // TODO add your handling code here:
        
          jTextFieldDisponivelMouseClicked(null);
        
        try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(null);
        }
        
    }//GEN-LAST:event_jTextFieldDisponivelDiaMouseExited

    private void jTextFieldDisponivelDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDisponivelDiaMousePressed
        // TODO add your handling code here:

        jTextFieldDisponivelMouseClicked(null);
        
        try{
        
                //Data Para Sql
                String dia = jFormattedTextFieldData_Fechamento.getText().substring(0,2);
                String mes = jFormattedTextFieldData_Fechamento.getText().substring(3,5);
                String ano = jFormattedTextFieldData_Fechamento.getText().substring(6,10);
                String hora = jFormattedTextFieldData_Fechamento.getText().substring(11,13);
                String minuto = jFormattedTextFieldData_Fechamento.getText().substring(14,16);
                ModContas.setData_Pagamento(ano+"-"+mes+"-"+dia+" "+hora+":"+minuto);
                
        ControlContas.Valor_DsponivelPrazo_Dia(ModContas);
        ControlContas.Valor_Dsponivel_Dia(ModContas);
        
        Float Res_TotalDisponivelDia = (ModContas.getValor_Disponivel()+ModContas.getValor_Disponivel2());
        
       //Formatar
       //VL_Moeda = NumberFormat.getInstance();
       //VL_Moeda.setMaximumFractionDigits(2);             
       
       //jTextFieldDisponivelDia.setText(String.valueOf(VL_Moeda.format(Res_TotalDisponivelDia)));
       
        
       jTextFieldDisponivelDia.setText(String.valueOf((Res_TotalDisponivelDia)));
       
       
        }catch (Exception e){
           
           jFormattedTextFieldData_Fechamento.setText(jFormattedTextFieldData.getText());
            jTextFieldDisponivelDiaMouseClicked(null);
        }
        
    }//GEN-LAST:event_jTextFieldDisponivelDiaMousePressed

    private void jFormattedTextField_RetiradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_RetiradaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == 44){
            
            jFormattedTextField_Retirada.setText(jFormattedTextField_Retirada.getText()+".");
            
        }
        
    }//GEN-LAST:event_jFormattedTextField_RetiradaKeyPressed

    private void jFormattedTextField_RetiradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_RetiradaKeyReleased
        // TODO add your handling code here:
        
        if((evt.getKeyCode() < 48 || evt.getKeyCode() > 57) && (evt.getKeyCode() != 8 && evt.getKeyCode() !=46)){
            
            
            if(jFormattedTextField_Retirada.getText().length() >0) 
            jFormattedTextField_Retirada.setText(jFormattedTextField_Retirada.getText().substring(0, jFormattedTextField_Retirada.getText().length()-1));
            
        }
        
    }//GEN-LAST:event_jFormattedTextField_RetiradaKeyReleased


    public void PreencherTabela_Cargo (String sql){
        
        Conexao.conexao();
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Cod.FN","Fornecedor","CNPJ","Nº NF","Data Venc.","Data Emissão","Valor","Pagto","Data Pag."};
    
    
    Conexao.executaSQL(sql);
    
        try {
            Conexao.rs.first();
            
            do{
                dados.add(new Object [] {Conexao.rs.getInt("idfornecedor"),Conexao.rs.getString("nome_fornecedor"),Conexao.rs.getString("cnpj_fornecedor"),Conexao.rs.getString("Numero_NF"),Conexao.rs.getString("Data_vencimento"),Conexao.rs.getString("Data_Emissao"),Conexao.rs.getString("Valor_total_NF"),Conexao.rs.getString("Pagamento"),Conexao.rs.getString("Data_Pagamento")});
            }while (Conexao.rs.next()); 
                          
            } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Não à Válores em Aberto para Pagamento!");
        }
                
        ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        
        jTableCombustivel.setModel(modelo);
        
        jTableCombustivel.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableCombustivel.getColumnModel().getColumn(0).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableCombustivel.getColumnModel().getColumn(1).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTableCombustivel.getColumnModel().getColumn(2).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTableCombustivel.getColumnModel().getColumn(3).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableCombustivel.getColumnModel().getColumn(4).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableCombustivel.getColumnModel().getColumn(5).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(6).setPreferredWidth(70);
        jTableCombustivel.getColumnModel().getColumn(6).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(7).setPreferredWidth(70);
        jTableCombustivel.getColumnModel().getColumn(7).setResizable(false);
        jTableCombustivel.getColumnModel().getColumn(8).setPreferredWidth(120);
        jTableCombustivel.getColumnModel().getColumn(8).setResizable(false);
        
        
        jTableCombustivel.setAutoResizeMode(jTableCombustivel.AUTO_RESIZE_OFF);
        jTableCombustivel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Conexao.desconecta();
    
        
    }
    

public void Consultar_ID_VL (){
    
    Conexao.conexao();
    Conexao.executaSQL("select * from venda_pecas");
        try {
            Conexao.rs.last();
            
            ModContas.setId_VendaProdutos(Float.parseFloat(Conexao.rs.getString("idVenda_pecas")));
            
        } catch (SQLException ex) {
            Logger.getLogger(JI_ContasPagar.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}

public void Calcular_Disponivel (){
    
    Float Disponivel = Float.parseFloat(jTextFieldDisponivel.getText());
    Float VL_Baixa = Float.parseFloat(jTextFieldTotal_Pagamento.getText());
    
    TotalDisponivel_Restante = (Disponivel - VL_Baixa);
}
    
    public void Preencher_ComboStatus(){
        
        jComboBoxStatus_Pagamento.removeAllItems();
        
        jComboBoxStatus_Pagamento.addItem("-Sel-");
        jComboBoxStatus_Pagamento.addItem("Em Aberto");
        jComboBoxStatus_Pagamento.addItem("Pago");
        
    }
    
    public void Preencher_ComboFiltro (){
        
        jComboBoxFiltro_Pesquisa.removeAllItems();
        
        jComboBoxFiltro_Pesquisa.addItem("-Sel-");
        jComboBoxFiltro_Pesquisa.addItem("Situação do Pagamento");
        jComboBoxFiltro_Pesquisa.addItem("Código Fornecedor");
        jComboBoxFiltro_Pesquisa.addItem("Nome Fornecedor");
        jComboBoxFiltro_Pesquisa.addItem("Número da NF");
        jComboBoxFiltro_Pesquisa.addItem("Data de Vencimento");
        
    }
    
           public void Valores_TabelaPesquisa (){
          
           int Cod_Tabela, Cod_Fornecedor;        
          int Selecao = jTableCombustivel.getSelectedRow();
          Cod_Tabela = Integer.parseInt(jTableCombustivel.getModel().getValueAt(Selecao,3).toString());
          Cod_Fornecedor = Integer.parseInt(jTableCombustivel.getModel().getValueAt(Selecao,0).toString());
         // jTextFieldplaca.setText(jTabletabelaItensVenda.getModel().getValueAt(Selecao, ));

//        jTextFieldNumero_NF.setText(String.valueOf(Cod_Tabela));
  //      jTextFieldCodigoFornecedor.setText(String.valueOf(Cod_Fornecedor));
    
        ModContas.setNumero_NF_Contas(Cod_Tabela);
        ModContas.setCod_Fornecedor(Cod_Fornecedor);
        
ControlContas.PesquisarValor_Pagar(ModContas, ModFornecedor);

jTextFieldTotal_Pagamento.setText(String.valueOf(ModContas.getValor_Total_Pagar()));
jTextFieldNumero_NF.setText(String.valueOf(ModContas.getNumero_NF_Contas()));
jTextFieldCodigoFornecedor.setText(String.valueOf(ModContas.getCod_Fornecedor()));
jTextFieldNome_Fornecedor.setText(String.valueOf(ModFornecedor.getNome_fornecedor()));





          }
           
           public void Hora_Atual_Sistema (){
        
    Date d = new Date();
    
    Locale Local = new Locale("pt","BR");
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    
    String Data = sdf.format(d);

    jFormattedTextFieldData.setText(Data);

        
    }
    
    
   public void Localizar_nomeUsuario (String Nome_user){
       
       Conexao.conexao();
       
       Conexao.executaSQL("SELECT * FROM login inner join funcionario_dados on login.`Funcionario_Dados_idFuncionario` = funcionario_dados.`idFuncionario` where login.`Nome_acesso`='"+Nome_user+"'");
       
        try {
            Conexao.rs.first();
            
           
            
        } catch (SQLException ex) {
            Logger.getLogger(JI_ContasPagar.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
   public void Buscar_Fechamento (){
       
       Conexao.conexao();
       
       Conexao.executaSQL("SELECT * FROM fechamento_caixa");
       
       try {
            Conexao.rs.last();
            
            String Data = Conexao.rs.getString("Data_fechamento");
            
            //jFormattedTextFieldData_Fechamento.setText(String.valueOf(Data));
            
        //Data Para Sql 2016/02/21 17:21
        String anoVenda = Data.substring(0,4);
        String mesVenda = Data.substring(5,7);
        String diaVenda = Data.substring(8,10);
        String horaVenda = Data.substring(11,13);
        String minutoVenda = Data.substring(14,16);
        
        jFormattedTextFieldData_Fechamento.setText(String.valueOf(diaVenda+"-"+mesVenda+"-"+anoVenda+" "+horaVenda+":"+minutoVenda)); 
        
        float VL_Retirada = Conexao.rs.getFloat("VL_Retirado");
        jFormattedTextField_Reservado.setText(String.valueOf(VL_Retirada));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não localizado fechamento anterior");
        }
    
       
   }
   
   
   public void Pesquisar_Usuario(){
       
       Conexao.conexao();
       
       Conexao.executaSQL("SELECT * FROM login where `Nome_acesso` ='"+ModFechamento.getNome_Usuario()+"'");
        try {
            Conexao.rs.first();
            
            ModFechamento.setId_LoginFechamento(Conexao.rs.getInt("idLogin"));
            
        } catch (SQLException ex) {
            Logger.getLogger(JI_ContasPagar.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
   }
   
   
public class Frm_AdicionarContas extends javax.swing.JFrame {

    /**
     * Creates new form Frm_AdicionarContas
     */
    public Frm_AdicionarContas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Contas a Pagar");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Descrição");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Total");

        jLabel4.setText("Número NF");

        jLabel5.setText("Fornecedor");

        jLabel6.setText("Data Emissão");

        jLabel7.setText("Data Vencimento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("ADICIONAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField3)
                            .addComponent(jFormattedTextField4)
                            .addComponent(jFormattedTextField5)
                            .addComponent(jFormattedTextField6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}

           
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddContas;
    private javax.swing.JButton jButtonFechar_Caixa;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxFiltro_Pesquisa;
    private javax.swing.JComboBox<String> jComboBoxStatus_Pagamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_Fechamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_Vencimento;
    private javax.swing.JFormattedTextField jFormattedTextField_Reservado;
    private javax.swing.JFormattedTextField jFormattedTextField_Retirada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelC_Pagarnome;
    private javax.swing.JLabel jLabelC_Pagarusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCombustivel;
    private javax.swing.JTextField jTextFieldCodigoFornecedor;
    private javax.swing.JFormattedTextField jTextFieldDisponivel;
    private javax.swing.JTextField jTextFieldDisponivelDia;
    private javax.swing.JTextField jTextFieldNome_Fornecedor;
    private javax.swing.JTextField jTextFieldNumero_NF;
    private javax.swing.JTextField jTextFieldTotal_Pagamento;
    // End of variables declaration//GEN-END:variables
}
