/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.BD.Conecta_Banco;
import Model.BO.FuncionarioBO;
import Model.DAO.FuncionarioDAO;
import Model.VO.Cadastro_FuncionarioVO;
import Model.VO.Cadastro_MarcaVO;
import Model.VO.Dados_iniciaisVO;
import Model.VO.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lucas
 */
public class JI_Funcionario extends javax.swing.JInternalFrame {

    
        Cadastro_FuncionarioVO ModFuncionario = new Cadastro_FuncionarioVO();
    
    FuncionarioDAO ControlFuncionario = new FuncionarioDAO();
    
    Conecta_Banco Conexao = new Conecta_Banco();
    
    Dados_iniciaisVO Dados_Inicio = new Dados_iniciaisVO();

    FuncionarioBO FuncionarioBO = new FuncionarioBO();
    
    int id;
    
    
    /**
     * Creates new form NewJInternalFrame
     */
    public JI_Funcionario() {
        initComponents();
        
                jTextFieldCodigo.setEnabled(false);
    
        PreencherComboEstado();
        PreencherComboFormacao();
//        PreencherComboProfissao();
        PreencherCargo();
        PreencherSetor();

        
                        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(false);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNovoRegistro = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButtonAtualizar_Registro = new javax.swing.JButton();
        jButtonModoPesquisa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNomefuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldcpf = new javax.swing.JFormattedTextField();
        jTextFieldrg = new javax.swing.JFormattedTextField();
        jTextFielddata_nascimento = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldendereco = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldnumero = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldbairro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldcomplemento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxestado = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldcidade = new javax.swing.JTextField();
        jTextFieldtelefone = new javax.swing.JFormattedTextField();
        jTextFieldcelular = new javax.swing.JFormattedTextField();
        jTextFieldcep = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxformacao1 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jComboBoxcargo1 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxsetor1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosFornecedor = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Funcionario");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/new-file-btn.png"))); // NOI18N
        jButtonNovoRegistro.setToolTipText("Inserir Registro");
        jButtonNovoRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovoRegistro.setContentAreaFilled(false);
        jButtonNovoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoRegistroActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/untitled_1.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Sign_Close_Icon_48.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Remover Registro");
        jButtonExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Back Button.png"))); // NOI18N
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Forward Button.png"))); // NOI18N
        jButtonProximo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/master-clean.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar Registro");
        jButtonLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Executar Pesquisa");
        jButtonPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SUPERMERCADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Logout_Icon_48.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButtonAtualizar_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Button_Refresh_Icon_32.png"))); // NOI18N
        jButtonAtualizar_Registro.setToolTipText("Alterar");
        jButtonAtualizar_Registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtualizar_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar_RegistroActionPerformed(evt);
            }
        });

        jButtonModoPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Remote Desktop.png"))); // NOI18N
        jButtonModoPesquisa.setToolTipText("Ativar Modo Pesquisa");
        jButtonModoPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNovoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Código");

        jLabel3.setText("Nome");

        jLabel4.setText("CPF");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Dados Pessoais");

        jLabel9.setText("Data Nascimento");

        jLabel10.setText("Idade");

        jTextFieldidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldidadeMouseClicked(evt);
            }
        });
        jTextFieldidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldidadeKeyTyped(evt);
            }
        });

        jLabel13.setText("RG");

        try {
            jTextFieldcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextFieldrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextFielddata_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomefuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldrg)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFielddata_nascimento)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomefuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddata_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Contato");

        jLabel16.setText("Endereço");

        jLabel17.setText("Número");

        jLabel18.setText("Bairro");

        jLabel19.setText("Complemento");

        jLabel20.setText("Telefone");

        jLabel21.setText("Celular");

        jLabel22.setText("Cep");

        jLabel23.setText("Estado");

        jComboBoxestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxestado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxestadoMouseClicked(evt);
            }
        });

        jLabel24.setText("Email");

        jLabel25.setText("Cidade");

        try {
            jTextFieldtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextFieldcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextFieldcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldbairro, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jTextFieldcep)))
                    .addComponent(jTextFieldemail))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel19)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldcidade, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jComboBoxestado, 0, 163, Short.MAX_VALUE)
                    .addComponent(jTextFieldcomplemento))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jComboBoxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Dados Profissionais");

        jLabel26.setText("Formação");

        jComboBoxformacao1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxformacao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxformacao1MouseClicked(evt);
            }
        });

        jLabel28.setText("Cargo");

        jComboBoxcargo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxcargo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxcargo1MouseClicked(evt);
            }
        });

        jLabel29.setText("Setor");

        jComboBoxsetor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxsetor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxsetor1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxformacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxcargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxsetor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBoxformacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jComboBoxcargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jComboBoxsetor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTableDadosFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDadosFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDadosFornecedor);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel30)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 818, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoRegistroActionPerformed
        // TODO add your handling code here:

        jButtonLimparActionPerformed(evt);

        jTextFieldCodigo.setEnabled(false);

        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoRegistroActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

            try {
                //Funcionario Dados
                ModFuncionario.setNome_Funcionario(jTextFieldNomefuncionario.getText());
                ModFuncionario.setData_Funcionario(jTextFielddata_nascimento.getText());
                ModFuncionario.setIdade_Funcionario(jTextFieldidade.getText());
                ModFuncionario.setCPF_funcionario(jTextFieldcpf.getText());
                ModFuncionario.setRG_funcionario(jTextFieldrg.getText());
                
//                ModFuncionario.setProfissao_NomeFuncionario((String) jComboBoxprofissao1.getSelectedItem());
                ModFuncionario.setFormacao_NomeFuncionario((String) jComboBoxformacao1.getSelectedItem());
                ModFuncionario.setSetor_NomeFuncionario((String) jComboBoxsetor1.getSelectedItem());
                ModFuncionario.setCargo_NomeFuncionario((String) jComboBoxcargo1.getSelectedItem());
                
                
                //Funcionario Contato
                ModFuncionario.setEndereco_Funcionario_Contato(jTextFieldendereco.getText());
                ModFuncionario.setNumero_Funcionario_Contato(jTextFieldnumero.getText());
                ModFuncionario.setBairro_Funcionario_Contato(jTextFieldbairro.getText());
                ModFuncionario.setComplemento_Funcionario_Contato(jTextFieldcomplemento.getText());
                ModFuncionario.setTelefone_Funcionario_Contato(jTextFieldtelefone.getText());
                ModFuncionario.setCelular_Funcionario_Contato(jTextFieldcelular.getText());
                ModFuncionario.setCep_Funcionario_Contato(jTextFieldcep.getText());
                ModFuncionario.setCidade_Funcionario_Contato(jTextFieldcidade.getText());
                ModFuncionario.setEmail_Funcionario(jTextFieldemail.getText());
                
                ModFuncionario.setEstado_NomeFuncionario_Contato((String) jComboBoxestado.getSelectedItem());
                ModFuncionario.setIDFuncionario_Dados(jTextFieldcpf.getText());
                

                FuncionarioBO.FuncionarioBO(ModFuncionario);

                Pesquisar_IDFuncionario();
                
            } catch (NumberFormatException ex) {
   
                JOptionPane.showMessageDialog(null, "Erro Valores! Verifique Campos Numéricos");
            Conexao.desconecta();
            
            }

        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:

              try {
Conexao.conexao();

Conexao.executaSQL("select * from funcionario_dados where idFuncionario ='"+jTextFieldCodigo.getText()+"'");
        
    
        Conexao.rs.first();
        
        String Cod_cliente = Conexao.rs.getString("idFuncionario");
        
        if (Cod_cliente != ""){
        
        if(JOptionPane.showConfirmDialog(null, "Confirmar Exclusão do registro", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

            Conexao.conexao();
            
            Conexao.executaSQLupdates("DELETE from funcionario_cotato where `Funcionario_Dados_idFuncionario`='"+Integer.parseInt(jTextFieldCodigo.getText())+"'");
            Conexao.executaSQLupdates("DELETE from funcionario_dados where `idFuncionario`='"+Integer.parseInt(jTextFieldCodigo.getText())+"'");
            
            JOptionPane.showMessageDialog(null, "Cadastro Removido com Sucesso!");

            jButtonLimparActionPerformed(evt);

            Conexao.desconecta();
            }
        
        }
    } catch (SQLException ex) {
        
        JOptionPane.showMessageDialog(null, "Registro Não Localizado!");
           
           Conexao.desconecta();
        
    }


        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:

          try {
    
    Conexao.conexao();
        
Conexao.executaSQL("select * from funcionario_dados where idFuncionario<'"+jTextFieldCodigo.getText()+"'");
       
    
 Conexao.rs.last();
           
          String id_Anterior = Conexao.rs.getString("idFuncionario");
           
           jTextFieldCodigo.setText(String.valueOf(id_Anterior));
          
            jButtonPesquisarActionPerformed(evt);
            
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Registro Anterior Não Localizado!");

        
       }        

        
                                                   

        
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed

                        try {
      Conexao.conexao();
        
Conexao.executaSQL("select * from funcionario_dados where idFuncionario>'"+jTextFieldCodigo.getText()+"'");
       
        Conexao.rs.first();
           
          String id_proximo = Conexao.rs.getString("idFuncionario");
           
          jTextFieldCodigo.setText(String.valueOf(id_proximo));
          
            jButtonPesquisarActionPerformed(evt);
           
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Próximo Registro Não Localizado!");
    
         
         
       }

        
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:

        jTextFieldCodigo.setText("");
        jTextFieldNomefuncionario.setText("");
        jTextFieldbairro.setText("");
        jTextFieldcelular.setText("");
        jTextFieldcep.setText("");
        jTextFieldcidade.setText("");
        jTextFieldcomplemento.setText("");
        jTextFieldcpf.setText("");
        jTextFielddata_nascimento.setText("");
        jTextFieldemail.setText("");
        jTextFieldendereco.setText("");
        jTextFieldidade.setText("");
        jTextFieldnumero.setText("");
        jTextFieldrg.setText("");
        jTextFieldtelefone.setText("");

        PreencherComboEstado();
        PreencherComboFormacao();
//        PreencherComboProfissao();
        PreencherCargo();
        PreencherSetor();

        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:

        
        String id;
        
        id = jTextFieldCodigo.getText();
        
        if(jTextFieldCodigo.getText().equals("")){

            ModFuncionario.setPesquisaNomeFuncionario(jTextFieldNomefuncionario.getText());

            PreencherTabelaProduto("select * from funcionario_dados inner join funcionario_cotato on funcionario_dados.`idFuncionario` = funcionario_cotato.`Funcionario_Dados_idFuncionario` inner join setor on funcionario_dados.`Setor_idSetor` = setor.`idSetor` inner join cargo on funcionario_dados.`Cargo_idCargo` = cargo.`idCargo` where funcionario_dados.`Nome_Funcionario` like'%"+ModFuncionario.getPesquisaNomeFuncionario()+"%'");

            ControlFuncionario.PesquisarNome_Funcionario(ModFuncionario);

            jTextFieldCodigo.setText(String.valueOf(ModFuncionario.getID_Funcionario()));
            jTextFieldNomefuncionario.setText(String.valueOf(ModFuncionario.getNome_Funcionario()));
            jTextFielddata_nascimento.setText(String.valueOf(ModFuncionario.getData_Funcionario()));
            jTextFieldidade.setText(String.valueOf(ModFuncionario.getIdade_Funcionario()));
            jTextFieldcpf.setText(String.valueOf(ModFuncionario.getCPF_funcionario()));
            jTextFieldrg.setText(String.valueOf(ModFuncionario.getRG_funcionario()));

            jTextFieldendereco.setText(String.valueOf(ModFuncionario.getEndereco_Funcionario_Contato()));
                jTextFieldnumero.setText(String.valueOf(ModFuncionario.getNumero_Funcionario_Contato()));
            jTextFieldbairro.setText(String.valueOf(ModFuncionario.getBairro_Funcionario_Contato()));
            jTextFieldcomplemento.setText(String.valueOf(ModFuncionario.getComplemento_Funcionario_Contato()));
            jTextFieldtelefone.setText(String.valueOf(ModFuncionario.getTelefone_Funcionario_Contato()));
            jTextFieldcelular.setText(String.valueOf(ModFuncionario.getCelular_Funcionario_Contato()));
            jTextFieldcep.setText(String.valueOf(ModFuncionario.getCep_Funcionario_Contato()));
            jTextFieldcidade.setText(String.valueOf(ModFuncionario.getCidade_Funcionario_Contato()));
            jTextFieldemail.setText(String.valueOf(ModFuncionario.getEmail_Funcionario()));

            jComboBoxestado.setSelectedItem(ModFuncionario.getEstado_NomeFuncionario_Contato());
            jComboBoxformacao1.setSelectedItem(ModFuncionario.getFormacao_NomeFuncionario());
           // jComboBoxprofissao1.setSelectedItem(ModFuncionario.getProfissao_NomeFuncionario());
            jComboBoxsetor1.setSelectedItem(ModFuncionario.getSetor_NomeFuncionario());
            jComboBoxcargo1.setSelectedItem(ModFuncionario.getCargo_NomeFuncionario());


                                            //Ativar Botões
        jButtonAtualizar_Registro.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);

            
        
        }else

        if(id != null){

            ModFuncionario.setID_Funcionario(Integer.parseInt(jTextFieldCodigo.getText()));

            PreencherTabelaProduto("select * from funcionario_dados inner join funcionario_cotato on funcionario_dados.`idFuncionario` = funcionario_cotato.`Funcionario_Dados_idFuncionario` inner join setor on funcionario_dados.`Setor_idSetor` = setor.`idSetor` inner join cargo on funcionario_dados.`Cargo_idCargo` = cargo.`idCargo` where funcionario_dados.`idFuncionario` ='"+ModFuncionario.getID_Funcionario()+"'");

            ControlFuncionario.PesquisarCod_Funcionario(ModFuncionario);

            jTextFieldCodigo.setText(String.valueOf(ModFuncionario.getID_Funcionario()));
            jTextFieldNomefuncionario.setText(String.valueOf(ModFuncionario.getNome_Funcionario()));
            jTextFielddata_nascimento.setText(String.valueOf(ModFuncionario.getData_Funcionario()));
            jTextFieldidade.setText(String.valueOf(ModFuncionario.getIdade_Funcionario()));
            jTextFieldcpf.setText(String.valueOf(ModFuncionario.getCPF_funcionario()));
            jTextFieldrg.setText(String.valueOf(ModFuncionario.getRG_funcionario()));

            jTextFieldendereco.setText(String.valueOf(ModFuncionario.getEndereco_Funcionario_Contato()));
            jTextFieldnumero.setText(String.valueOf(ModFuncionario.getNumero_Funcionario_Contato()));
            jTextFieldbairro.setText(String.valueOf(ModFuncionario.getBairro_Funcionario_Contato()));
            jTextFieldcomplemento.setText(String.valueOf(ModFuncionario.getComplemento_Funcionario_Contato()));
            jTextFieldtelefone.setText(String.valueOf(ModFuncionario.getTelefone_Funcionario_Contato()));
            jTextFieldcelular.setText(String.valueOf(ModFuncionario.getCelular_Funcionario_Contato()));
            jTextFieldcep.setText(String.valueOf(ModFuncionario.getCep_Funcionario_Contato()));
            jTextFieldcidade.setText(String.valueOf(ModFuncionario.getCidade_Funcionario_Contato()));
            jTextFieldemail.setText(String.valueOf(ModFuncionario.getEmail_Funcionario()));

            jComboBoxestado.setSelectedItem(ModFuncionario.getEstado_NomeFuncionario_Contato());
            jComboBoxformacao1.setSelectedItem(ModFuncionario.getFormacao_NomeFuncionario());
//            jComboBoxprofissao1.setSelectedItem(ModFuncionario.getProfissao_NomeFuncionario());
            jComboBoxsetor1.setSelectedItem(ModFuncionario.getSetor_NomeFuncionario());
            jComboBoxcargo1.setSelectedItem(ModFuncionario.getCargo_NomeFuncionario());
        
            
                                            //Ativar Botões
        jButtonAtualizar_Registro.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);

            
        }

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButtonAtualizar_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar_RegistroActionPerformed
        // TODO add your handling code here:

                        if(JOptionPane.showConfirmDialog(null, "Confirmar Alteração do registro", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

        
        ModFuncionario.setID_Funcionario(Integer.parseInt(jTextFieldCodigo.getText()));

        ModFuncionario.setNome_Funcionario(jTextFieldNomefuncionario.getText());
        ModFuncionario.setData_Funcionario(jTextFielddata_nascimento.getText());
        ModFuncionario.setIdade_Funcionario(jTextFieldidade.getText());
        ModFuncionario.setCPF_funcionario(jTextFieldcpf.getText());
        ModFuncionario.setRG_funcionario(jTextFieldrg.getText());

//        ModFuncionario.setProfissao_NomeFuncionario((String) jComboBoxprofissao1.getSelectedItem());
        ModFuncionario.setFormacao_NomeFuncionario((String) jComboBoxformacao1.getSelectedItem());
        ModFuncionario.setSetor_NomeFuncionario((String) jComboBoxsetor1.getSelectedItem());
        ModFuncionario.setCargo_NomeFuncionario((String) jComboBoxcargo1.getSelectedItem());

        ModFuncionario.setEndereco_Funcionario_Contato(jTextFieldendereco.getText());
        ModFuncionario.setNumero_Funcionario_Contato(jTextFieldnumero.getText());
        ModFuncionario.setBairro_Funcionario_Contato(jTextFieldbairro.getText());
        ModFuncionario.setComplemento_Funcionario_Contato(jTextFieldcomplemento.getText());
        ModFuncionario.setTelefone_Funcionario_Contato(jTextFieldtelefone.getText());
        ModFuncionario.setCelular_Funcionario_Contato(jTextFieldcelular.getText());
        ModFuncionario.setCep_Funcionario_Contato(jTextFieldcep.getText());
        ModFuncionario.setCidade_Funcionario_Contato(jTextFieldcidade.getText());
        ModFuncionario.setEmail_Funcionario(jTextFieldemail.getText());

        ModFuncionario.setEstado_NomeFuncionario_Contato((String) jComboBoxestado.getSelectedItem());

        ControlFuncionario.AtualizarFuncionario(ModFuncionario);

                        }
        
    }//GEN-LAST:event_jButtonAtualizar_RegistroActionPerformed

    private void jButtonModoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoPesquisaActionPerformed
        // TODO add your handling code here:

        jButtonLimparActionPerformed(evt);

        jTextFieldCodigo.setEnabled(true);
        
        jButtonPesquisar.setEnabled(true);

        
        
    }//GEN-LAST:event_jButtonModoPesquisaActionPerformed

    private void jTableDadosFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosFornecedorMouseClicked
        // TODO add your handling code here:
        
        Valores_TabelaPesquisa();
        
        jButtonPesquisarActionPerformed(null);
        
    }//GEN-LAST:event_jTableDadosFornecedorMouseClicked

    private void jComboBoxformacao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxformacao1MouseClicked
        // TODO add your handling code here:
        
        PreencherComboFormacao();
        
    }//GEN-LAST:event_jComboBoxformacao1MouseClicked

    private void jComboBoxcargo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxcargo1MouseClicked
        // TODO add your handling code here:
        
        PreencherCargo();
        
    }//GEN-LAST:event_jComboBoxcargo1MouseClicked

    private void jComboBoxsetor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxsetor1MouseClicked
        // TODO add your handling code here:
        
        PreencherSetor();
        
    }//GEN-LAST:event_jComboBoxsetor1MouseClicked

    private void jComboBoxestadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxestadoMouseClicked
        // TODO add your handling code here:
        
        PreencherComboEstado();
        
    }//GEN-LAST:event_jComboBoxestadoMouseClicked

    private void jTextFieldidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldidadeMouseClicked
        // TODO add your handling code here:
        
                   int Idade_AddInt;      
        
   try {
       
       Idade_AddInt = Integer.parseInt(jTextFieldidade.getText());
   
       if(jTextFieldidade.getText().equals("")){
            
            jTextFieldidade.setText("0");
            
        }else{
           
           if(Idade_AddInt <= 0){
               
               jTextFieldidade.setText("0");
               
           }
           
       }
       
   }catch (NumberFormatException ex){

      jTextFieldidade.setText("0");
       
   }

        
    }//GEN-LAST:event_jTextFieldidadeMouseClicked

    private void jTextFieldidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldidadeKeyPressed
        // TODO add your handling code here:
        
        int Idade_AddInt;      
        
   try {
       
       Idade_AddInt = Integer.parseInt(jTextFieldidade.getText());
   
       if(jTextFieldidade.getText().equals("")){
            
            jTextFieldidade.setText("0");
            
        }else{
           
           if(Idade_AddInt <= 0){
               
               jTextFieldidade.setText("0");
               
           }
           
       }
       
   }catch (NumberFormatException ex){

      jTextFieldidade.setText("0");
       
   }
        
    }//GEN-LAST:event_jTextFieldidadeKeyPressed

    private void jTextFieldidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldidadeKeyReleased
        // TODO add your handling code here:
        
        int Idade_AddInt;      
        
   try {
       
       Idade_AddInt = Integer.parseInt(jTextFieldidade.getText());
   
       if(jTextFieldidade.getText().equals("")){
            
            jTextFieldidade.setText("0");
            
        }else{
           
           if(Idade_AddInt <= 0){
               
               jTextFieldidade.setText("0");
               
           }
           
       }
       
   }catch (NumberFormatException ex){

      jTextFieldidade.setText("0");
       
   }
        
    }//GEN-LAST:event_jTextFieldidadeKeyReleased

    private void jTextFieldidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldidadeKeyTyped
        // TODO add your handling code here:
        
        int Idade_AddInt;      
        
   try {
       
       Idade_AddInt = Integer.parseInt(jTextFieldidade.getText());
   
       if(jTextFieldidade.getText().equals("")){
            
            jTextFieldidade.setText("0");
            
        }else{
           
           if(Idade_AddInt <= 0){
               
               jTextFieldidade.setText("0");
               
           }
           
       }
       
   }catch (NumberFormatException ex){

      jTextFieldidade.setText("0");
       
   }
        
    }//GEN-LAST:event_jTextFieldidadeKeyTyped


        public void PreencherTabelaProduto (String slq){
        
        //Conecta_Banco Conexao = new Conecta_Banco();
    
        Conexao.conexao();
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código", "Nome", "CPF","Telefone","Cargo","Setor"};
    
    
    Conexao.executaSQL(slq);
    
        try {
            Conexao.rs.first();
            
            do{
                dados.add(new Object [] {Conexao.rs.getString("idFuncionario"),Conexao.rs.getString("Nome_Funcionario"),Conexao.rs.getString("CPF_Funcionario"),Conexao.rs.getString("Telefone_Funcionario"),Conexao.rs.getString("Nome_Cargo"),Conexao.rs.getString("Nome_Setor")});
            }while (Conexao.rs.next()); 
                          
            } catch (Exception ex) {
            // JOptionPane.showMessageDialog(null, "Erro no preenchimento do Array List "+ex);
        }
                
        ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        
        jTableDadosFornecedor.setModel(modelo);
        
        jTableDadosFornecedor.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableDadosFornecedor.getColumnModel().getColumn(0).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(1).setPreferredWidth(262);
        jTableDadosFornecedor.getColumnModel().getColumn(1).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableDadosFornecedor.getColumnModel().getColumn(2).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableDadosFornecedor.getColumnModel().getColumn(3).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(4).setPreferredWidth(135);
        jTableDadosFornecedor.getColumnModel().getColumn(4).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(5).setPreferredWidth(135);
        jTableDadosFornecedor.getColumnModel().getColumn(5).setResizable(false);
        
        jTableDadosFornecedor.getTableHeader().setReorderingAllowed(false);
        
        jTableDadosFornecedor.setAutoResizeMode(jTableDadosFornecedor.AUTO_RESIZE_OFF);
        jTableDadosFornecedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Conexao.desconecta();
        
    }
    
    public void PreencherComboEstado(){
        
        Conexao.conexao();
        
        Conexao.executaSQL("select * from estado order by nome_estado");
        
        try {
            Conexao.rs.first();
            
            jComboBoxestado.removeAllItems();
            jComboBoxestado.addItem(Dados_Inicio.getCombobox_selecionar());
            do{
                
                jComboBoxestado.addItem(Conexao.rs.getString("nome_estado"));
                
            }while(Conexao.rs.next());
            
        } catch (SQLException ex) {
          //  Logger.getLogger(JI_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Conexao.desconecta();
        
    }
    
    
    
    public void PreencherComboFormacao(){
        
        Conexao.conexao();
        
        Conexao.executaSQL("select * from formacao order by Nome_Formacao");
        
        try {
            Conexao.rs.first();
            
            jComboBoxformacao1.removeAllItems();
            jComboBoxformacao1.addItem(Dados_Inicio.getCombobox_selecionar());
            
            do{
                jComboBoxformacao1.addItem(Conexao.rs.getString("Nome_Formacao"));
                
            }while (Conexao.rs.next());
            
        } catch (SQLException ex) {
          //  Logger.getLogger(JI_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Conexao.desconecta();
    }
    
    
/*    
    public void PreencherComboProfissao(){
        
        Conexao.conexao();
        
        Conexao.executaSQL("select * from profissao order by Nome_Profissao");
        
        try {
            Conexao.rs.first();
            
            jComboBoxprofissao1.removeAllItems();
            jComboBoxprofissao1.addItem(Dados_Inicio.getCombobox_selecionar());
            
            do{
                jComboBoxprofissao1.addItem(Conexao.rs.getString("Nome_Profissao"));
                
            }while(Conexao.rs.next());
            
        } catch (SQLException ex) {
           // Logger.getLogger(JI_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Conexao.desconecta();
        
    }
    
  */  
    
    public void PreencherCargo (){
        
        Conexao.conexao();
        
        Conexao.executaSQL("select * from cargo order by Nome_Cargo");
        
        try {
            Conexao.rs.first();
            
            jComboBoxcargo1.removeAllItems();
            jComboBoxcargo1.addItem(Dados_Inicio.getCombobox_selecionar());
            
            do{
                jComboBoxcargo1.addItem(Conexao.rs.getString("Nome_Cargo"));
                
            }while (Conexao.rs.next());
            
        } catch (SQLException ex) {
           // Logger.getLogger(JI_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Conexao.desconecta();
        
    }
    
    
    
    
    public void PreencherSetor(){
        
        Conexao.conexao();
        
        Conexao.executaSQL("select * from setor order by Nome_Setor");
        
        try {
            Conexao.rs.first();
            
            jComboBoxsetor1.removeAllItems();
            jComboBoxsetor1.addItem(Dados_Inicio.getCombobox_selecionar());
            
            do{
                
                jComboBoxsetor1.addItem(Conexao.rs.getString("Nome_Setor"));
                
            }while (Conexao.rs.next());
            
        } catch (SQLException ex) {
           // Logger.getLogger(JI_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Conexao.desconecta();
        
    }

    
    
    
    
            public void Valores_TabelaPesquisa (){
          
          int Cod_Tabela;         
          int Selecao = jTableDadosFornecedor.getSelectedRow();
          Cod_Tabela = Integer.parseInt(jTableDadosFornecedor.getModel().getValueAt(Selecao,0).toString());
         // jTextFieldplaca.setText(jTabletabelaItensVenda.getModel().getValueAt(Selecao, ));
          ModFuncionario.setID_Funcionario(Cod_Tabela);
         
        jTextFieldCodigo.setText(String.valueOf(ModFuncionario.getID_Funcionario()));
        
           
 }
            
            
            public void Pesquisar_IDFuncionario (){
                
                Conexao.conexao();
                Conexao.executaSQL("select * from funcionario_dados");
                
            try {
                Conexao.rs.last();
                
                id = Conexao.rs.getInt("idFuncionario");
                
                jTextFieldCodigo.setText(String.valueOf(id));
                
                
            } catch (SQLException ex) {
               
                    
                }
                
            
            }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtualizar_Registro;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonModoPesquisa;
    private javax.swing.JButton jButtonNovoRegistro;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxcargo1;
    private javax.swing.JComboBox jComboBoxestado;
    private javax.swing.JComboBox jComboBoxformacao1;
    private javax.swing.JComboBox jComboBoxsetor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDadosFornecedor;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomefuncionario;
    private javax.swing.JTextField jTextFieldbairro;
    private javax.swing.JFormattedTextField jTextFieldcelular;
    private javax.swing.JFormattedTextField jTextFieldcep;
    private javax.swing.JTextField jTextFieldcidade;
    private javax.swing.JTextField jTextFieldcomplemento;
    private javax.swing.JFormattedTextField jTextFieldcpf;
    private javax.swing.JFormattedTextField jTextFielddata_nascimento;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldidade;
    private javax.swing.JTextField jTextFieldnumero;
    private javax.swing.JFormattedTextField jTextFieldrg;
    private javax.swing.JFormattedTextField jTextFieldtelefone;
    // End of variables declaration//GEN-END:variables
}
