/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.BD.Conecta_Banco;
import Model.BO.FornecedorBO;
import Model.DAO.PecasDAO;
import Model.VO.Cadastro_MarcaVO;
import Model.VO.ModeloTabela;
import Model.VO.SCadastro_Fornecedores;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lucas
 */
public class JI_Fornecedor extends javax.swing.JInternalFrame {

    
   SCadastro_Fornecedores ModFornecedor = new SCadastro_Fornecedores();
    
    PecasDAO ControlFornecedor = new PecasDAO();
    
    Conecta_Banco Conexao = new Conecta_Banco();   

    FornecedorBO FornecedorBO = new FornecedorBO();
    
    int Id_FN;
    
    /**
     * Creates new form NewJInternalFrame
     */
    public JI_Fornecedor() {
        initComponents();
        
        jTextFieldCodigo.setEnabled(false);
        
        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNovoRegistro = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButtonAtualizar_Registro = new javax.swing.JButton();
        jButtonModoPesquisa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNomefornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldobservacao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldendereco_fornecedor = new javax.swing.JTextField();
        jTextFieldbairro_fornecedor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldramal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldcnpjfornecedor = new javax.swing.JFormattedTextField();
        jTextFieldtelefone_fornecedor = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextFieldcelular2 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosFornecedor = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Fornecedor");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/new-file-btn.png"))); // NOI18N
        jButtonNovoRegistro.setToolTipText("Inserir Registro");
        jButtonNovoRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovoRegistro.setContentAreaFilled(false);
        jButtonNovoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoRegistroActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/untitled_1.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Sign_Close_Icon_48.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Remover Registro");
        jButtonExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Back Button.png"))); // NOI18N
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Forward Button.png"))); // NOI18N
        jButtonProximo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/master-clean.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar Registro");
        jButtonLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Executar Pesquisa");
        jButtonPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Cannon BJ 100SPPM.png"))); // NOI18N
        jButton10.setToolTipText("Imprimir");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SUPERMERCADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Logout_Icon_48.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButtonAtualizar_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Button_Refresh_Icon_32.png"))); // NOI18N
        jButtonAtualizar_Registro.setToolTipText("Alterar");
        jButtonAtualizar_Registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtualizar_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar_RegistroActionPerformed(evt);
            }
        });

        jButtonModoPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Remote Desktop.png"))); // NOI18N
        jButtonModoPesquisa.setToolTipText("Ativar Modo Pesquisa");
        jButtonModoPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNovoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Código");

        jLabel3.setText("Nome Fornecedor");

        jLabel4.setText("CNPJ");

        jLabel5.setText("Telefone");

        jLabel6.setText("Observação");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cadastro/Consulta");

        jLabel17.setText("Endereço");

        jLabel18.setText("Bairro");

        jTextFieldendereco_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldendereco_fornecedorActionPerformed(evt);
            }
        });

        jLabel19.setText("Ramal");

        jLabel7.setText("Celular ");

        jLabel8.setText("Celular 2");

        try {
            jTextFieldcnpjfornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextFieldtelefone_fornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextFieldcelular2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldNomefornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldendereco_fornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldtelefone_fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldramal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldcelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldbairro_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldcnpjfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldobservacao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomefornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldcnpjfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldendereco_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldbairro_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldramal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldtelefone_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldobservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableDadosFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDadosFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDadosFornecedor);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 818, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoRegistroActionPerformed
        // TODO add your handling code here:

        jButtonLimparActionPerformed(evt);

        jTextFieldCodigo.setEnabled(false);
        
        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoRegistroActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        //Conecta_Banco Conexao = new Conecta_Banco();

        try {

            ModFornecedor.setNome_fornecedor(jTextFieldNomefornecedor.getText());
            ModFornecedor.setCnpj_fornecedor(jTextFieldcnpjfornecedor.getText());
            ModFornecedor.setEndereco_fornecedor(jTextFieldendereco_fornecedor.getText());
            ModFornecedor.setBairro_fornecedor(jTextFieldbairro_fornecedor.getText());
            ModFornecedor.setTelefone_fornecedor(jTextFieldtelefone_fornecedor.getText());
            ModFornecedor.setRamal_fornecedor(jTextFieldramal.getText());
            ModFornecedor.setCelular1_fornecedor(jFormattedTextField1.getText());
            ModFornecedor.setCelular2_fornecedor(jTextFieldcelular2.getText());
            ModFornecedor.setObservacao_fornecedor(jTextFieldobservacao.getText());

//            ControlFornecedor.CadastroFornecedores(ModFornecedor);

            FornecedorBO.Fornecedor_BO(ModFornecedor);
            Pesquisar_IDFornecedor();

            
        } catch (NumberFormatException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro Valores! Verifique Campos Numéricos");
            
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:

               try {
           
        Conexao.conexao();

        Conexao.executaSQL("select * from fornecedor where idfornecedor ='"+jTextFieldCodigo.getText()+"'");
       
           Conexao.rs.first();
        
           String Cod_Fornecedor = Conexao.rs.getString("idfornecedor");
           
           if(Cod_Fornecedor != ""){
          
              
        if(JOptionPane.showConfirmDialog(null, "Deseja Excluir o Registro?","Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){

            Conexao.conexao();

            Conexao.executaSQLupdates("delete from fornecedor where idfornecedor='"+Integer.parseInt(jTextFieldCodigo.getText())+"'");
            JOptionPane.showMessageDialog(null, "Fonecedor Excluido com Sucesso!");

            jButtonLimparActionPerformed(evt);
            
           Conexao.desconecta();
           
           }
       }
           
       } catch (SQLException ex) {
           
           JOptionPane.showMessageDialog(null, "Registro Não Localizado!");
           
           Conexao.desconecta();
       }
        
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:

        try {
    
    Conexao.conexao();
        
Conexao.executaSQL("select * from fornecedor where idfornecedor<'"+jTextFieldCodigo.getText()+"'");
       
    
 Conexao.rs.last();
           
          String id_Anterior = Conexao.rs.getString("idfornecedor");
           
           jTextFieldCodigo.setText(String.valueOf(id_Anterior));
          
            jButtonPesquisarActionPerformed(evt);
            
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Registro Anterior Não Localizado!");

        
       }        

        
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed

                try {
      Conexao.conexao();
        
Conexao.executaSQL("select * from fornecedor where idfornecedor>'"+jTextFieldCodigo.getText()+"'");
       
        Conexao.rs.first();
           
          String id_proximo = Conexao.rs.getString("idfornecedor");
           
          jTextFieldCodigo.setText(String.valueOf(id_proximo));
          
            jButtonPesquisarActionPerformed(evt);
           
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Próximo Registro Não Localizado!");
    
         
         
       }

        
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:

        jTextFieldCodigo.setText("");
        jTextFieldNomefornecedor.setText("");
        jTextFieldcnpjfornecedor.setText("");
        jTextFieldendereco_fornecedor.setText("");
        jTextFieldbairro_fornecedor.setText("");
        jTextFieldtelefone_fornecedor.setText("");
        jTextFieldramal.setText("");
        jFormattedTextField1.setText("");
        jTextFieldcelular2.setText("");
        jTextFieldobservacao.setText("");

//        PreencherTabelaProduto("");
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:

        String id;
        
        id = jTextFieldCodigo.getText();
        
        if(jTextFieldCodigo.getText().equals("")){

            ModFornecedor.setPesquisaNomeFornecedor(jTextFieldNomefornecedor.getText());

            PreencherTabelaProduto("select * from fornecedor where nome_fornecedor like'%"+jTextFieldNomefornecedor.getText()+"%'");

            ControlFornecedor.PesquisaNomeFornecedor(ModFornecedor);

            jTextFieldCodigo.setText(String.valueOf(ModFornecedor.getId_fornecedor()));
            jTextFieldNomefornecedor.setText(String.valueOf(ModFornecedor.getNome_fornecedor()));
            jTextFieldcnpjfornecedor.setText(String.valueOf(ModFornecedor.getCnpj_fornecedor()));
            jTextFieldendereco_fornecedor.setText(String.valueOf(ModFornecedor.getEndereco_fornecedor()));
            jTextFieldbairro_fornecedor.setText(String.valueOf(ModFornecedor.getBairro_fornecedor()));
            jTextFieldtelefone_fornecedor.setText(String.valueOf(ModFornecedor.getTelefone_fornecedor()));
            jTextFieldramal.setText(String.valueOf(ModFornecedor.getRamal_fornecedor()));
            jFormattedTextField1.setText(String.valueOf(ModFornecedor.getCelular1_fornecedor()));
            jTextFieldcelular2.setText(String.valueOf(ModFornecedor.getCelular2_fornecedor()));
            jTextFieldobservacao.setText(String.valueOf(ModFornecedor.getObservacao_fornecedor()));

                                //Ativar Botões
        jButtonAtualizar_Registro.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);

            
        }else

        if(id != null){

            ModFornecedor.setPesquisaFornecedor(Integer.parseInt(jTextFieldCodigo.getText()));

            ControlFornecedor.ConsultarIDFornecedor(ModFornecedor);

            jTextFieldCodigo.setText(String.valueOf(ModFornecedor.getId_fornecedor()));
            jTextFieldNomefornecedor.setText(String.valueOf(ModFornecedor.getNome_fornecedor()));
            jTextFieldcnpjfornecedor.setText(String.valueOf(ModFornecedor.getCnpj_fornecedor()));
            jTextFieldendereco_fornecedor.setText(String.valueOf(ModFornecedor.getEndereco_fornecedor()));
            jTextFieldbairro_fornecedor.setText(String.valueOf(ModFornecedor.getBairro_fornecedor()));
            jTextFieldtelefone_fornecedor.setText(String.valueOf(ModFornecedor.getTelefone_fornecedor()));
            jTextFieldramal.setText(String.valueOf(ModFornecedor.getRamal_fornecedor()));
            jFormattedTextField1.setText(String.valueOf(ModFornecedor.getCelular1_fornecedor()));
            jTextFieldcelular2.setText(String.valueOf(ModFornecedor.getCelular2_fornecedor()));
            jTextFieldobservacao.setText(String.valueOf(ModFornecedor.getObservacao_fornecedor()));

            PreencherTabelaProduto("select * from fornecedor where idfornecedor='"+jTextFieldCodigo.getText()+"'");

                                //Ativar Botões
        jButtonAtualizar_Registro.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);

            
        }

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButtonAtualizar_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar_RegistroActionPerformed
        // TODO add your handling code here:

                        if(JOptionPane.showConfirmDialog(null, "Confirmar Alteração do registro", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

        
        ModFornecedor.setAlterarFornecedor(Integer.parseInt(jTextFieldCodigo.getText()));

        ModFornecedor.setNome_fornecedor(jTextFieldNomefornecedor.getText());
        ModFornecedor.setCnpj_fornecedor(jTextFieldcnpjfornecedor.getText());
        ModFornecedor.setEndereco_fornecedor(jTextFieldendereco_fornecedor.getText());
        ModFornecedor.setBairro_fornecedor(jTextFieldbairro_fornecedor.getText());
        ModFornecedor.setTelefone_fornecedor(jTextFieldtelefone_fornecedor.getText());
        ModFornecedor.setRamal_fornecedor(jTextFieldramal.getText());
        ModFornecedor.setCelular1_fornecedor(jFormattedTextField1.getText());
        ModFornecedor.setCelular2_fornecedor(jTextFieldcelular2.getText());
        ModFornecedor.setObservacao_fornecedor(jTextFieldobservacao.getText());

        ControlFornecedor.AtualizarFornecedor(ModFornecedor);

        PreencherTabelaProduto("select * from fornecedor where idfornecedor='"+jTextFieldCodigo.getText()+"'");

                        }
        
    }//GEN-LAST:event_jButtonAtualizar_RegistroActionPerformed

    private void jButtonModoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoPesquisaActionPerformed
        // TODO add your handling code here:

        jButtonLimparActionPerformed(evt);

        jTextFieldCodigo.setEnabled(true);
        

        jButtonPesquisar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonModoPesquisaActionPerformed

    private void jTextFieldendereco_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldendereco_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldendereco_fornecedorActionPerformed

    private void jTableDadosFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosFornecedorMouseClicked
        // TODO add your handling code here:
        
        Valores_TabelaPesquisa();
        
        jButtonPesquisarActionPerformed(null);
        
    }//GEN-LAST:event_jTableDadosFornecedorMouseClicked

    
            public void Valores_TabelaPesquisa (){
          
          int Cod_Tabela;         
          int Selecao = jTableDadosFornecedor.getSelectedRow();
          Cod_Tabela = Integer.parseInt(jTableDadosFornecedor.getModel().getValueAt(Selecao,0).toString());
         // jTextFieldplaca.setText(jTabletabelaItensVenda.getModel().getValueAt(Selecao, ));
          ModFornecedor.setId_fornecedor(Cod_Tabela);
     
        JOptionPane.showMessageDialog(null, ModFornecedor.getId_fornecedor());
        
        jTextFieldCodigo.setText(String.valueOf(ModFornecedor.getId_fornecedor()));
        
               
    }

    

    public void PreencherTabelaProduto (String slq){
        
        //Conecta_Banco Conexao = new Conecta_Banco();
    
        Conexao.conexao();
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código", "Nome", "CNPJ","Telefone"};
    
    
    Conexao.executaSQL(slq);
    
        try {
            Conexao.rs.first();
            
            do{
                dados.add(new Object [] {Conexao.rs.getString("idfornecedor"),Conexao.rs.getString("nome_fornecedor"),Conexao.rs.getString("cnpj_fornecedor"),Conexao.rs.getString("telefone_fornecedor")});
            }while (Conexao.rs.next()); 
                          
            } catch (Exception ex) {
            // JOptionPane.showMessageDialog(null, "Erro no preenchimento do Array List "+ex);
        }
                
        ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        
        jTableDadosFornecedor.setModel(modelo);
        
        jTableDadosFornecedor.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableDadosFornecedor.getColumnModel().getColumn(0).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(1).setPreferredWidth(380);
        jTableDadosFornecedor.getColumnModel().getColumn(1).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(2).setPreferredWidth(190);
        jTableDadosFornecedor.getColumnModel().getColumn(2).setResizable(false);
        jTableDadosFornecedor.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableDadosFornecedor.getColumnModel().getColumn(3).setResizable(false);
        jTableDadosFornecedor.getTableHeader().setReorderingAllowed(false);
        jTableDadosFornecedor.setAutoResizeMode(jTableDadosFornecedor.AUTO_RESIZE_OFF);
        jTableDadosFornecedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Conexao.desconecta();
        
    }
    
    
    public void Pesquisar_IDFornecedor (){
        
        //Informar Cód do Fornecedor
            Conexao.conexao();
            Conexao.executaSQL("select * from fornecedor");

       try {
           Conexao.rs.last();
           
            Id_FN = Conexao.rs.getInt("idfornecedor");

            jTextFieldCodigo.setText(String.valueOf(Id_FN));
                   
           
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao preencher ID "+ex);
       }
           
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtualizar_Registro;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonModoPesquisa;
    private javax.swing.JButton jButtonNovoRegistro;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDadosFornecedor;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomefornecedor;
    private javax.swing.JTextField jTextFieldbairro_fornecedor;
    private javax.swing.JFormattedTextField jTextFieldcelular2;
    private javax.swing.JFormattedTextField jTextFieldcnpjfornecedor;
    private javax.swing.JTextField jTextFieldendereco_fornecedor;
    private javax.swing.JTextField jTextFieldobservacao;
    private javax.swing.JTextField jTextFieldramal;
    private javax.swing.JFormattedTextField jTextFieldtelefone_fornecedor;
    // End of variables declaration//GEN-END:variables
}
