/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.BD.Conecta_Banco;
import Model.DAO.FuncionarioDAO;
import Model.DAO.LoginDAO;
import Model.VO.Cadastro_ClienteVO;
import Model.VO.Cadastro_FuncionarioVO;
import Model.VO.Cadastro_LoginVO;
import Model.VO.Dados_iniciaisVO;
import Model.VO.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lucas
 */
public class JI_LoginCadastro extends javax.swing.JInternalFrame {

    
    Cadastro_FuncionarioVO ModFuncionario = new Cadastro_FuncionarioVO();
    
    Conecta_Banco Conexao = new Conecta_Banco();
    
    Conecta_Banco Conexao2 = new Conecta_Banco();
    
    FuncionarioDAO ControlFuncionario = new FuncionarioDAO();

    Dados_iniciaisVO Dados_Inicio = new Dados_iniciaisVO();
    
    Cadastro_LoginVO ModLogin = new Cadastro_LoginVO();
    
    LoginDAO ControlLogin = new LoginDAO();
    
    
    /**
     * Creates new form NewJInternalFrame
     */
    public JI_LoginCadastro() {
        initComponents();
        
                        //Desabilitar Botões
        
                                jTextFieldCodigoFuncionario.setEnabled(true);
        jTextFieldNomeFuncionario.setEnabled(false);
        jTextFieldNome_acesso.setEnabled(false);
        jComboBoxPermissao.setEnabled(false);
        jPasswordFieldsenha_acesso.setEnabled(false);
        

        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(true);

                        
        
        //jLabelUserCadastroLogin.setText(User);
        
        Preencher_comboPermissao();

       
        jButtonPesquisar_Funcionario.setVisible(false);
        
        Conexao.conexao();
        
    }

    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNovo_Registro = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonAtualizar_Registro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Login = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jButtonPesquisar_Funcionario = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNome_acesso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldsenha_acesso = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxPermissao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonListarLogin = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Usuários");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovo_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/new-file-btn.png"))); // NOI18N
        jButtonNovo_Registro.setToolTipText("Inserir Registro");
        jButtonNovo_Registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovo_Registro.setContentAreaFilled(false);
        jButtonNovo_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo_RegistroActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/untitled_1.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Sign_Close_Icon_48.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Remover Registro");
        jButtonExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Back Button.png"))); // NOI18N
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Forward Button.png"))); // NOI18N
        jButtonProximo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/master-clean.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar Registro");
        jButtonLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Executar Pesquisa");
        jButtonPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SUPERMERCADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Logout_Icon_48.png"))); // NOI18N
        jButtonSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonAtualizar_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Button_Refresh_Icon_32.png"))); // NOI18N
        jButtonAtualizar_Registro.setToolTipText("Alterar");
        jButtonAtualizar_Registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtualizar_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar_RegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButtonNovo_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNovo_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_Login.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_LoginMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Login);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Código");

        jLabel3.setText("Nome");

        jButtonPesquisar_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search - Copia (2).png"))); // NOI18N
        jButtonPesquisar_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisar_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeFuncionario)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonPesquisar_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Usuário");

        jLabel8.setText("Senha");

        jLabel9.setText("Permissao de Acesso");

        jComboBoxPermissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPasswordFieldsenha_acesso, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addGap(69, 69, 69))
                        .addComponent(jComboBoxPermissao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldNome_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNome_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordFieldsenha_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Identificação");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cadastro Login");

        jButtonListarLogin.setText("Listar Login Cadastrados");
        jButtonListarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jButtonListarLogin))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 818, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovo_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo_RegistroActionPerformed
        // TODO add your handling code here:

        jButtonLimparActionPerformed(evt);
        
        
    }//GEN-LAST:event_jButtonNovo_RegistroActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:

            String Login = jTextFieldNome_acesso.getText(), Senha = jPasswordFieldsenha_acesso.getText(), Acesso = (String) jComboBoxPermissao.getSelectedItem();
            
            
        if(Login.equals("")){
            
            JOptionPane.showMessageDialog(null, "Erro: Digite o Login!");
            
        }else{
            if(Senha.equals("")){
                JOptionPane.showMessageDialog(null, "Erro: Digite a Senha!");
            
            }else{
                
           
                 if(Acesso.equals("--Sel--")){
                    JOptionPane.showMessageDialog(null, "Erro: Selecione o Tipo de Acesso!");
            
                }else{
                
                    
                         
    Conexao2.conexao();
        Conexao2.executaSQL("SELECT * FROM login where `Nome_acesso`='"+jTextFieldNome_acesso.getText()+"'");
        
try {      
        
            Conexao2.rs.first();
        
            String Nome_login = Conexao2.rs.getString("Nome_acesso");
            
           if(Nome_login == Login){
             //if(teste_nome == ""){
                              
           }else{
               
               JOptionPane.showMessageDialog(null, "Login Já em Uso!");
           
           }   
                             

            
        } catch (SQLException ex) {
             
             
        ModLogin.setNome_acesso(jTextFieldNome_acesso.getText());
        ModLogin.setSenha(jPasswordFieldsenha_acesso.getText());
        ModLogin.setPermissao((String) jComboBoxPermissao.getSelectedItem());
        ModLogin.setIdFuncionario(Integer.parseInt(jTextFieldCodigoFuncionario.getText()));

        ControlLogin.Cadastrar_novoLogin(ModLogin);

        JOptionPane.showMessageDialog(null, "Cadastrado Com Sucesso!");
        
        jButtonListarLoginActionPerformed(evt);
     
                        
                                     
                                
                           }
                      }
                
            
                }    
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:

               try {
           
        Conexao.conexao();

        Conexao.executaSQL("select * from funcionario_dados where idFuncionario ='"+jTextFieldCodigoFuncionario.getText()+"'");
        
       
           Conexao.rs.first();
        
           String Cod_Funcionario = Conexao.rs.getString("idFuncionario");
           
           if(Cod_Funcionario != ""){
          

        
                        if(JOptionPane.showConfirmDialog(null, "Confirmar exclusão do registro", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

        
        Conexao.conexao();

        Conexao.executaSQLupdates("delete from login where Funcionario_Dados_idFuncionario='"+Integer.parseInt(jTextFieldCodigoFuncionario.getText())+"'");

        Conexao.desconecta();

                            jButtonNovo_RegistroActionPerformed(evt);
        
                        }
                        
                               }
           
       } catch (SQLException ex) {
           
           JOptionPane.showMessageDialog(null, "Registro Não Localizado!");
                jButtonLimparActionPerformed(evt);
                    Conexao.desconecta();
       }

        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:

        try {
    
    Conexao.conexao();
        
Conexao.executaSQL("select * from login where idLogin<'"+jTextFieldCodigoFuncionario.getText()+"'");
       
    
 Conexao.rs.last();
           
          String id_Anterior = Conexao.rs.getString("idLogin");
           
           jTextFieldCodigoFuncionario.setText(String.valueOf(id_Anterior));
          
            jButtonPesquisarActionPerformed(evt);
            
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Registro Anterior Não Localizado!");

        
       }        
        

        
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:

        jTextFieldCodigoFuncionario.setText("");
        jTextFieldNomeFuncionario.setText("");
        jTextFieldNome_acesso.setText("");
        jPasswordFieldsenha_acesso.setText("");
        
        Preencher_comboPermissao();
        
                jTextFieldCodigoFuncionario.setEnabled(true);
        jTextFieldNomeFuncionario.setEnabled(false);
        jTextFieldNome_acesso.setEnabled(false);
        jComboBoxPermissao.setEnabled(false);
        jPasswordFieldsenha_acesso.setEnabled(false);
        

        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(true);

        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
try {
           
        Conexao.conexao();

        Conexao.executaSQL("select * from funcionario_dados where idFuncionario ='"+jTextFieldCodigoFuncionario.getText()+"'");
        
       
           Conexao.rs.first();
        
           String Cod_Funcionario = Conexao.rs.getString("idFuncionario");
           
           if(Cod_Funcionario != ""){
          
        
        
        int id = Integer.parseInt(jTextFieldCodigoFuncionario.getText());
    
        ModLogin.setIdFuncionario(Integer.parseInt(jTextFieldCodigoFuncionario.getText()));
        
    ControlLogin.ConsultarLogin(ModLogin);
    
    if(id == 0){
        
//        jButtonPesquisar_FuncionarioActionPerformed(evt);
  
ModLogin.setIdFuncionario(Integer.parseInt(jTextFieldCodigoFuncionario.getText()));
        
    ControlLogin.Pesquisar_Funcionario(ModLogin);
        
    jTextFieldCodigoFuncionario.setText(String.valueOf(ModLogin.getIdFuncionario()));
    jTextFieldNomeFuncionario.setText(String.valueOf(ModLogin.getNome_funcionario()));



    }else{
                
                jButtonPesquisar_FuncionarioActionPerformed(evt);
          
   
    
    jTextFieldCodigoFuncionario.setText(String.valueOf(ModLogin.getIdFuncionario()));
    jTextFieldNomeFuncionario.setText(String.valueOf(ModLogin.getNome_funcionario()));
    jTextFieldNome_acesso.setText(String.valueOf(ModLogin.getNome_acesso()));
    jPasswordFieldsenha_acesso.setText(String.valueOf(ModLogin.getSenha()));
    
    jComboBoxPermissao.setSelectedItem(ModLogin.getPermissao());

    
    
    //Campos
        jTextFieldCodigoFuncionario.setEnabled(false);
        jTextFieldNomeFuncionario.setEnabled(false);
        jTextFieldNome_acesso.setEnabled(true);
        jComboBoxPermissao.setEnabled(true);
        jPasswordFieldsenha_acesso.setEnabled(true);
        

        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);
        jButtonPesquisar.setEnabled(false);

        
            
            if(id == 0)
                
                jButtonPesquisar_FuncionarioActionPerformed(evt);
                
            }
    
    }
           
       } catch (SQLException ex) {
           
           JOptionPane.showMessageDialog(null, "Registro Não Localizado!");
                jButtonLimparActionPerformed(evt);
                    Conexao.desconecta();
       }

    
    
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAtualizar_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar_RegistroActionPerformed
        // TODO add your handling code here:

         if(JOptionPane.showConfirmDialog(null, "Confirmar Alteração do registro", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){


             ModLogin.setIdFuncionario(Integer.parseInt(jTextFieldCodigoFuncionario.getText()));
             
             ModLogin.setNome_acesso(jTextFieldNome_acesso.getText());
             ModLogin.setSenha(jPasswordFieldsenha_acesso.getText());
             ModLogin.setPermissao((String) jComboBoxPermissao.getSelectedItem());
             
             ControlLogin.Atualizar_login(ModLogin);

         }
        
    }//GEN-LAST:event_jButtonAtualizar_RegistroActionPerformed

    private void jTable_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_LoginMouseClicked
        // TODO add your handling code here:
        
        Valores_TabelaPesquisa();
        
        jButtonPesquisarActionPerformed(null);
        
        
    }//GEN-LAST:event_jTable_LoginMouseClicked

    private void jButtonPesquisar_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisar_FuncionarioActionPerformed
        // TODO add your handling code here:

        ModLogin.setIdFuncionario(Integer.parseInt(jTextFieldCodigoFuncionario.getText()));

        ControlLogin.Pesquisar_Funcionario(ModLogin);

        jTextFieldCodigoFuncionario.setText(String.valueOf(ModLogin.getIdFuncionario()));
        jTextFieldNomeFuncionario.setText(String.valueOf(ModLogin.getNome_funcionario()));

    }//GEN-LAST:event_jButtonPesquisar_FuncionarioActionPerformed

    private void jButtonListarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarLoginActionPerformed
        // TODO add your handling code here:
        
        PreencherTabela_Login("SELECT * FROM login order by `Nome_acesso`");
        
    }//GEN-LAST:event_jButtonListarLoginActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        
                try {
      Conexao.conexao();
        
Conexao.executaSQL("select * from login where idLogin>'"+jTextFieldCodigoFuncionario.getText()+"'");
      
        Conexao.rs.first();
           
          String id_proximo = Conexao.rs.getString("idLogin");
           
          jTextFieldCodigoFuncionario.setText(String.valueOf(id_proximo));
          
            jButtonPesquisarActionPerformed(evt);
           
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Próximo Registro Não Localizado!");
    
         
         
       }

        
    }//GEN-LAST:event_jButtonProximoActionPerformed


    public void PreencherTabela_Login (String sql){
    
    Conexao.conexao();
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código", "Nome", "Permissão"};
    
    
    Conexao.executaSQL(sql);
    
        try {
            Conexao.rs.first();
            
            do{
                dados.add(new Object [] {Conexao.rs.getString("Funcionario_Dados_idFuncionario"),Conexao.rs.getString("Nome_acesso"),Conexao.rs.getString("Permissao")});
            }while (Conexao.rs.next()); 
                          
            } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Erro no preenchimento do Array List "+ex);
        }
                
        ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        
        jTable_Login.setModel(modelo);
        
        jTable_Login.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_Login.getColumnModel().getColumn(0).setResizable(false);
        jTable_Login.getColumnModel().getColumn(1).setPreferredWidth(510);
        jTable_Login.getColumnModel().getColumn(1).setResizable(false);
        jTable_Login.getColumnModel().getColumn(2).setPreferredWidth(170);
        jTable_Login.getColumnModel().getColumn(2).setResizable(false);
        

        jTable_Login.setAutoResizeMode(jTable_Login.AUTO_RESIZE_OFF);
        jTable_Login.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Conexao.desconecta();
        
    }
    
    
    public void Preencher_comboPermissao (){
         
            jComboBoxPermissao.removeAllItems();
            jComboBoxPermissao.addItem(Dados_Inicio.getCombobox_selecionar()); 
            
                            
                jComboBoxPermissao.addItem("Administrador");
                jComboBoxPermissao.addItem("Padrão");
                jComboBoxPermissao.addItem("Básico");
           
        
    }
    
    
            public void Valores_TabelaPesquisa (){
          
          int Cod_Tabela;         
          int Selecao = jTable_Login.getSelectedRow();
         
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtualizar_Registro;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonListarLogin;
    private javax.swing.JButton jButtonNovo_Registro;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisar_Funcionario;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxPermissao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldsenha_acesso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Login;
    private javax.swing.JTextField jTextFieldCodigoFuncionario;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    private javax.swing.JTextField jTextFieldNome_acesso;
    // End of variables declaration//GEN-END:variables
}
