/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.BD.Conecta_Banco;
import Model.BO.Adicionar_ProdutosBO;
import Model.DAO.PecasDAO;
import Model.VO.Cadastro_MarcaVO;
import Model.VO.Dados_iniciaisVO;
import Model.VO.ModeloTabela;
import Model.VO.SCadastro_Fabricante;
import Model.VO.SCadastro_PecasVO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lucas
 */
public class JI_Pecas extends javax.swing.JInternalFrame {

    SCadastro_PecasVO ModPecas = new SCadastro_PecasVO();
    SCadastro_Fabricante Mod_Fabricante = new SCadastro_Fabricante();
    
    PecasDAO ControlPecas = new PecasDAO();
    
    Conecta_Banco Conexao = new Conecta_Banco();
   
    Dados_iniciaisVO Dados_Iniciais = new Dados_iniciaisVO();
    
    Adicionar_ProdutosBO ProdutosBO = new Adicionar_ProdutosBO();
    
        
    /**
     * Creates new form NewJInternalFrame
     */
    public JI_Pecas() {
        initComponents();
        
        jTextFieldCodigo.setEnabled(false);
        
        
         //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(false);


        Preencher_ComboCategoria();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonAtualizar_Registro = new javax.swing.JButton();
        jButtonModoPesquisa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNomePeca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldFabricante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCod_Barras = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListarPecas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Produtos");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/new-file-btn.png"))); // NOI18N
        jButtonNovo.setToolTipText("Inserir Registro");
        jButtonNovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovo.setContentAreaFilled(false);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/untitled_1.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Sign_Close_Icon_48.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Remover Registro");
        jButtonExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Back Button.png"))); // NOI18N
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Forward Button.png"))); // NOI18N
        jButtonProximo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/master-clean.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar Registro");
        jButtonLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Executar Pesquisa");
        jButtonPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SUPERMERCADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Logout_Icon_48.png"))); // NOI18N
        jButtonSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonAtualizar_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Button_Refresh_Icon_32.png"))); // NOI18N
        jButtonAtualizar_Registro.setToolTipText("Alterar");
        jButtonAtualizar_Registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtualizar_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar_RegistroActionPerformed(evt);
            }
        });

        jButtonModoPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Remote Desktop.png"))); // NOI18N
        jButtonModoPesquisa.setToolTipText("Cancelar Pesquisa");
        jButtonModoPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Código");

        jLabel3.setText("Nome do Produto");

        jLabel9.setText("Fabricante");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cadastro/Consulta");

        jLabel16.setText("Categoria");

        jLabel4.setText("Cód. Barras");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCod_Barras)
                                    .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCod_Barras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Listar/Consulta");

        jTableListarPecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarPecas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarPecasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListarPecas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 818, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:

        jButtonLimparActionPerformed(evt);

        jTextFieldCodigo.setEnabled(false);

        
        //Desabilitar Botões
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(false);

        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:

        int cod_pecas;
        ModPecas.setNome_pecas(jTextFieldNomePeca.getText());
        ModPecas.setAplicacao((String) jComboBoxCategoria.getSelectedItem());

        ModPecas.setFabricante(jTextFieldFabricante.getText());

        ModPecas.setCod_Barras(jTextFieldCod_Barras.getText());
        
        ProdutosBO.Verificar_Produtos(ModPecas);

        Registo_Cadastro();
        

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:

               try {
           
        Conexao.conexao();

        Conexao.executaSQL("select * from pecas where idPecas ='"+jTextFieldCodigo.getText()+"'");
        
       
           Conexao.rs.first();
        
           String Cod_Pecas = Conexao.rs.getString("idPecas");
           
           if(Cod_Pecas != ""){

        
        Conexao.conexao();
        
                if(JOptionPane.showConfirmDialog(null, "Confirmar Exclusão do registro", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

        
        Conexao.executaSQLupdates("delete from pecas where idPecas='"+jTextFieldCodigo.getText()+"'");

                }
           }
                       } catch (SQLException ex) {
           
           JOptionPane.showMessageDialog(null, "Registro Não Localizado!");
           
           Conexao.desconecta();
       }

                
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:

        try {
    
    Conexao.conexao();
        
Conexao.executaSQL("select * from pecas where idPecas<'"+jTextFieldCodigo.getText()+"'");
       
    
 Conexao.rs.last();
           
          String id_Anterior = Conexao.rs.getString("idPecas");
           
           jTextFieldCodigo.setText(String.valueOf(id_Anterior));
          
            jButtonPesquisarActionPerformed(evt);
            
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Registro Anterior Não Localizado!");

        
       }        
                                                   

        
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        
        try {
      Conexao.conexao();
        
Conexao.executaSQL("select * from pecas where idPecas>'"+jTextFieldCodigo.getText()+"'");
       
        Conexao.rs.first();
           
          String id_proximo = Conexao.rs.getString("idPecas");
           
          jTextFieldCodigo.setText(String.valueOf(id_proximo));
          
            jButtonPesquisarActionPerformed(evt);
           
       } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null, "Próximo Registro Não Localizado!");
    
                  
       }
        
        
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:

        jTextFieldCodigo.setText("");
        jTextFieldNomePeca.setText("");
        jTextFieldFabricante.setText("");
        //jTextFieldaplicacao.setText("");
        jTextFieldCod_Barras.setText("");
               
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:

String id;

id = jTextFieldCodigo.getText();

        if(jTextFieldCodigo.getText().equals("")){

            ModPecas.setPesquisaNomePeca(jTextFieldNomePeca.getText());

            ControlPecas.Pesquisar_NomePecas(ModPecas);

            jTextFieldCodigo.setText(String.valueOf(ModPecas.getId_pecas()));
            jTextFieldNomePeca.setText(String.valueOf(ModPecas.getNome_pecas()));
            jTextFieldFabricante.setText(String.valueOf(ModPecas.getFabricante()));
            jTextFieldCod_Barras.setText(String.valueOf(ModPecas.getCod_Barras()));
            PreencherTabelaPecas("select * from pecas where nome_peca like '%"+ModPecas.getPesquisaNomePeca()+"%'");

                                //Ativar Botões
        jButtonAtualizar_Registro.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);

            
        }else

        if (id != null){

            ModPecas.setPesquisaIDPecas(Integer.parseInt(jTextFieldCodigo.getText()));

            ControlPecas.ConsultarPecasID(ModPecas);

            jTextFieldCodigo.setText(String.valueOf(ModPecas.getId_pecas()));
            jTextFieldNomePeca.setText(String.valueOf(ModPecas.getNome_pecas()));
            jTextFieldFabricante.setText(String.valueOf(ModPecas.getFabricante()));
            jTextFieldCod_Barras.setText(String.valueOf(ModPecas.getCod_Barras()));

            
            PreencherTabelaPecas("select * from pecas where idPecas ='"+ModPecas.getPesquisaIDPecas()+"'");

                                //Ativar Botões
        jButtonAtualizar_Registro.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(true);

            
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAtualizar_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar_RegistroActionPerformed
        // TODO add your handling code here:

                        if(JOptionPane.showConfirmDialog(null, "Confirmar Alteração do registro", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_NO_OPTION){

        
        ModPecas.setPesquisaIDPecas(Integer.parseInt(jTextFieldCodigo.getText()));

        ModPecas.setNome_pecas(jTextFieldNomePeca.getText());
        ModPecas.setAplicacao((String) jComboBoxCategoria.getSelectedItem());
        ModPecas.setFabricante(jTextFieldFabricante.getText());
        ModPecas.setCod_Barras(jTextFieldCod_Barras.getText());

        ControlPecas.AtualizarRegistro(ModPecas);

                        }
        
    }//GEN-LAST:event_jButtonAtualizar_RegistroActionPerformed

    private void jButtonModoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoPesquisaActionPerformed
        // TODO add your handling code here:

        jTextFieldCodigo.setEnabled(true);

        jButtonPesquisar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonModoPesquisaActionPerformed

    private void jTableListarPecasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarPecasMouseClicked
        // TODO add your handling code here:
        
        Valores_TabelaPesquisa();

        jButtonPesquisarActionPerformed(null);
        
    }//GEN-LAST:event_jTableListarPecasMouseClicked


    
        
    
    public void PreencherTabelaPecas (String sql){
        
        Conexao.conexao();
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código", "Descrição", "Cod. de Barras","Fabricante"};
    
    
    Conexao.executaSQL(sql);
    
        try {
            Conexao.rs.first();
            
            do{
                dados.add(new Object [] {Conexao.rs.getString("idPecas"),Conexao.rs.getString("nome_peca"),Conexao.rs.getString("Cod_Barras"),Conexao.rs.getString("fabricante_pecas_idfabricante_pecas")});
            }while (Conexao.rs.next()); 
                          
            } catch (Exception ex) {
            // JOptionPane.showMessageDialog(null, "Erro no preenchimento do Array List "+ex);
        }
                
        ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        
        jTableListarPecas.setModel(modelo);
        
        jTableListarPecas.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableListarPecas.getColumnModel().getColumn(0).setResizable(false);
        jTableListarPecas.getColumnModel().getColumn(1).setPreferredWidth(450);
        jTableListarPecas.getColumnModel().getColumn(1).setResizable(false);
        jTableListarPecas.getColumnModel().getColumn(2).setPreferredWidth(170);
        jTableListarPecas.getColumnModel().getColumn(2).setResizable(false);
        jTableListarPecas.getColumnModel().getColumn(3).setPreferredWidth(170);
        jTableListarPecas.getColumnModel().getColumn(3).setResizable(false);
        
        jTableListarPecas.setAutoResizeMode(jTableListarPecas.AUTO_RESIZE_OFF);
        jTableListarPecas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Conexao.desconecta();
        
    }


            public void Valores_TabelaPesquisa (){
          
          int Cod_Tabela;         
          int Selecao = jTableListarPecas.getSelectedRow();
          Cod_Tabela = Integer.parseInt(jTableListarPecas.getModel().getValueAt(Selecao,0).toString());
         // jTextFieldplaca.setText(jTabletabelaItensVenda.getModel().getValueAt(Selecao, ));
          ModPecas.setId_pecas(Cod_Tabela);
   
        
        jTextFieldCodigo.setText(String.valueOf(ModPecas.getId_pecas()));   
         
    }

    
            public void Preencher_ComboCategoria (){
                
             jComboBoxCategoria.removeAllItems();
             jComboBoxCategoria.addItem("-Sel-");
                
             jComboBoxCategoria.addItem("Cereais");
             jComboBoxCategoria.addItem("Frutas");
             jComboBoxCategoria.addItem("Verduras");
            }
            
       public void Registo_Cadastro (){
           
        Conexao.conexao();
        
        Conexao.executaSQL("select * from pecas");
        try {
            Conexao.rs.last();

            String cod_pecas = Conexao.rs.getString("idPecas");
            jTextFieldCodigo.setText(String.valueOf(cod_pecas));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Nenhum Registro Localizado!");
        }
            
       }     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtualizar_Registro;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonModoPesquisa;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListarPecas;
    private javax.swing.JTextField jTextFieldCod_Barras;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldFabricante;
    private javax.swing.JTextField jTextFieldNomePeca;
    // End of variables declaration//GEN-END:variables
}
