/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.BD.Conecta_Banco;
import Model.DAO.EstoqueDAO;
import Model.DAO.PecasDAO;
import Model.VO.Cadastro_FuncionarioVO;
import Model.VO.Cadastro_MarcaVO;
import Model.VO.Cadastro_NFVO;
import Model.VO.Dados_iniciaisVO;
import Model.VO.Estoque_ProdutosVO;
import Model.VO.ModeloTabela;
import Model.VO.SCadastro_Fabricante;
import Model.VO.SCadastro_PecasVO;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import static mondrian.olap.fun.vba.Vba.date;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import static org.apache.poi.hssf.usermodel.HeaderFooter.date;
import static org.apache.xalan.lib.ExsltDatetime.date;
import static org.joda.time.format.ISODateTimeFormat.date;

/**
 *
 * @author Lucas
 */
public class RE_Estoque extends javax.swing.JInternalFrame {

    SCadastro_PecasVO ModPecas = new SCadastro_PecasVO();
    SCadastro_Fabricante Mod_Fabricante = new SCadastro_Fabricante();

        Estoque_ProdutosVO ModEstoque = new Estoque_ProdutosVO();
        Cadastro_NFVO ModNF = new Cadastro_NFVO();

        Conecta_Banco Conexao = new Conecta_Banco();
   
    Dados_iniciaisVO Dados_Iniciais = new Dados_iniciaisVO();
    
    Cadastro_FuncionarioVO ModFuncionario = new Cadastro_FuncionarioVO();
    
    EstoqueDAO ControlEstoque = new EstoqueDAO();
    
    Frm_Principal Dados_User;
    
    String Tipo_SelecaoRelatorio;
    
    /**
     * Creates new form NewJInternalFrame
     */
    public RE_Estoque(String Nome_User) {
        initComponents();
        
        jLabelUser.setText(Nome_User);
        
        //Desabilitar Botões
        jButtonSalvar.setEnabled(false);
        jButtonAtualizar_Registro.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonModoPesquisa.setEnabled(false);
        
        Conexao.conexao();

    PreencherCombo_TipoRelatorio();
    Preencher_ComboCategoria();
    Preencher_ComboTipoPesquisa();

//Proteger campos
jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

    
    }


   
    

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonAtualizar_Registro = new javax.swing.JButton();
        jButtonModoPesquisa = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNomePeca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonPesquisaCliente1 = new javax.swing.JButton();
        jButtonPesquisaCliente2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jFormattedTextFieldData_Validade_inicial = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        jFormattedTextFieldData_Validade_Final = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEstoque_Inicial = new javax.swing.JTextField();
        jTextFieldEstoque_Final = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxTipoPesquisa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButtonGerar_Relatorio = new javax.swing.JButton();
        jComboBoxTipo_relatorio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Estoque de Produtos");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/new-file-btn.png"))); // NOI18N
        jButtonNovo.setToolTipText("Inserir Registro");
        jButtonNovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovo.setContentAreaFilled(false);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/untitled_1.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Sign_Close_Icon_48.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Remover Registro");
        jButtonExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Back Button.png"))); // NOI18N
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Forward Button.png"))); // NOI18N
        jButtonProximo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/master-clean.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar Registro");
        jButtonLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Executar Pesquisa");
        jButtonPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUPERMERCADO");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Logout_Icon_48.png"))); // NOI18N
        jButtonSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonAtualizar_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Button_Refresh_Icon_32.png"))); // NOI18N
        jButtonAtualizar_Registro.setToolTipText("Alterar");
        jButtonAtualizar_Registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtualizar_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar_RegistroActionPerformed(evt);
            }
        });

        jButtonModoPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Remote Desktop.png"))); // NOI18N
        jButtonModoPesquisa.setToolTipText("Cancelar Pesquisa");
        jButtonModoPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoPesquisaActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel27.setForeground(java.awt.Color.blue);
        jLabel27.setText("Usuario Logado");

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabelUser.setForeground(java.awt.Color.blue);
        jLabelUser.setText("Nome Usuário");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAtualizar_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonModoPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addGap(5, 5, 5)
                .addComponent(jLabelUser))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Código");

        jLabel3.setText("Nome do Produto");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Contrua Seu Critério");

        jButtonPesquisaCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search - Copia.png"))); // NOI18N
        jButtonPesquisaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaCliente1ActionPerformed(evt);
            }
        });

        jButtonPesquisaCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/Search - Copia.png"))); // NOI18N
        jButtonPesquisaCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaCliente2ActionPerformed(evt);
            }
        });

        jLabel28.setText("Data Validade Inicial.");

        try {
            jFormattedTextFieldData_Validade_inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel29.setText("Data Validade Final");

        try {
            jFormattedTextFieldData_Validade_Final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Quant. Estoque Inicial");

        jLabel5.setText("Quant. Estoque Final");

        jLabel16.setText("Categoria");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTipoPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoPesquisaItemStateChanged(evt);
            }
        });
        jComboBoxTipoPesquisa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPesquisaMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPesquisaMouseMoved(evt);
            }
        });
        jComboBoxTipoPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxTipoPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxTipoPesquisaFocusLost(evt);
            }
        });
        jComboBoxTipoPesquisa.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jComboBoxTipoPesquisaMouseWheelMoved(evt);
            }
        });
        jComboBoxTipoPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPesquisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPesquisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPesquisaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPesquisaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPesquisaMouseReleased(evt);
            }
        });
        jComboBoxTipoPesquisa.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxTipoPesquisaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBoxTipoPesquisa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxTipoPesquisaPropertyChange(evt);
            }
        });
        jComboBoxTipoPesquisa.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBoxTipoPesquisaVetoableChange(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Critério Pesquisa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel1))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(348, 348, 348))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel29)
                            .addComponent(jLabel3)
                            .addComponent(jLabel28)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFormattedTextFieldData_Validade_Final, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldData_Validade_inicial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEstoque_Inicial)
                                    .addComponent(jTextFieldEstoque_Final, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNomePeca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonPesquisaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButtonPesquisaCliente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPesquisaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jFormattedTextFieldData_Validade_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jFormattedTextFieldData_Validade_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEstoque_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEstoque_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Config. Relatório");

        jButtonGerar_Relatorio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGerar_Relatorio.setText("Gerar Relatório");
        jButtonGerar_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerar_RelatorioActionPerformed(evt);
            }
        });

        jComboBoxTipo_relatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTipo_relatorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipo_relatorioItemStateChanged(evt);
            }
        });

        jLabel6.setText("Tipo de Relatório");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(72, 72, 72)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipo_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGerar_Relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipo_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGerar_Relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 818, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:


        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:


        

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:


                
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:


        
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:

jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAtualizar_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar_RegistroActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButtonAtualizar_RegistroActionPerformed

    private void jButtonModoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoPesquisaActionPerformed
        // TODO add your handling code here:

        jTextFieldCodigo.setEnabled(true);

        jButtonPesquisar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonModoPesquisaActionPerformed

    private void jButtonPesquisaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaCliente1ActionPerformed
        // TODO add your handling code here:

            ModPecas.setNome_pecas(jTextFieldNomePeca.getText());
        
        RE_Estoque.Frm_ProdutoPesquisa Frm_ProdutoPesquisa = new RE_Estoque.Frm_ProdutoPesquisa();
        
        Frm_ProdutoPesquisa.PreencherTabela_PesquisaProduto("select * from pecas where nome_peca like '%"+jTextFieldNomePeca.getText()+"%'");
        
        Frm_ProdutoPesquisa.setVisible(true);
   
        
    }//GEN-LAST:event_jButtonPesquisaCliente1ActionPerformed

    private void jButtonPesquisaCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaCliente2ActionPerformed
        // TODO add your handling code here:
              
        Conexao.conexao();
        Conexao.executaSQL("select * from estoque where Pecas_idPecas='"+jTextFieldCodigo.getText()+"'");
        try {
            Conexao.rs.first();
            
            if(Conexao.rs.getString("Pecas_idPecas").equals("")){
                
            }else{

                ModPecas.setId_pecas(Integer.parseInt(jTextFieldCodigo.getText()));
        
        ControlEstoque.Pesquisar_VendasPecas(ModPecas);
        
        jTextFieldCodigo.setText(String.valueOf(ModPecas.getId_pecas()));
        jTextFieldNomePeca.setText(String.valueOf(ModPecas.getNome_pecas()));
        
                
            }
                  
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Registro Não Localizado!");
                        
        }
        
        
    }//GEN-LAST:event_jButtonPesquisaCliente2ActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonGerar_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerar_RelatorioActionPerformed
        
    String Cod = jTextFieldCodigo.getText();
    String Produto = jTextFieldNomePeca.getText(), 
    Data_Inicial = jFormattedTextFieldData_Validade_inicial.getText(), 
    Data_Final = jFormattedTextFieldData_Validade_Final.getText(), Categoria = (String) jComboBoxCategoria.getSelectedItem(), 
    Tipo_Relatorio = (String) jComboBoxTipo_relatorio.getSelectedItem();
    
    String Estoque_Inicial_String = jTextFieldEstoque_Inicial.getText();
    String Estoque_Final_String = jTextFieldEstoque_Final.getText();
    
    
    String Data_Inicial_String = jFormattedTextFieldData_Validade_inicial.getText(), 
            Data_Final_String = jFormattedTextFieldData_Validade_Final.getText();
    
/*    
    try{
    Float Estoque_Inicial = Float.parseFloat(jTextFieldEstoque_Inicial.getText());
    Float Estoque_Final = Float.parseFloat(jTextFieldEstoque_Final.getText());
    
        
    if(Estoque_Inicial >=5 ){

    
        try {
        
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where estoque.`Quant_em_estoque` >='"+Estoque_Inicial+"' and estoque.`Quant_em_estoque` <='"+Estoque_Final+"'");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/RelatorioEstoque.jasper", new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }

    }
   
    }catch (NumberFormatException ex2){
        
    }finally{
       
    */

/*
if((jTextFieldCodigo.getText().equals("")) && (jTextFieldNomePeca.getText().equals("")) 
        && jTextFieldEstoque_Inicial.getText().equals("") && jComboBoxCategoria.getSelectedItem().equals("-Sel-")) {

        try {
        
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas`");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/RelatorioEstoque.jasper", new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }
            
}else{

*/

    if(jTextFieldCodigo.getText().equals("") && jComboBoxCategoria.getSelectedItem().equals("-Sel-")
                && jTextFieldEstoque_Inicial.getText().equals("") && jTextFieldEstoque_Final.getText().equals("") &&
            jTextFieldNomePeca.getText().equals("") && (jFormattedTextFieldData_Validade_inicial.getText().equals("  -  -    "))
            && (jFormattedTextFieldData_Validade_Final.getText().equals("  -  -    "))){
    
//        JOptionPane.showMessageDialog(null, "Tudo null");
        //Relatório Geral
                 try {
//        JOptionPane.showMessageDialog(null, "Tudo null try");
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas`");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }
    
  
    }else{
                 
    //Pesquisa por ID
        if( (Cod != "") && jComboBoxCategoria.getSelectedItem().equals("-Sel-") && (Produto != "")
                && jTextFieldEstoque_Inicial.getText().equals("") && jTextFieldEstoque_Final.getText().equals("")
                && (jFormattedTextFieldData_Validade_inicial.getText().equals("  -  -    "))
            && (jFormattedTextFieldData_Validade_Final.getText().equals("  -  -    "))){
    
            //Fazer outro if com as condições de id e nome
            
            if (jTextFieldCodigo.getText().equals("")){
                
                //Por nome "iReport/"+Tipo_SelecaoRelatorio, n
              try {
        JOptionPane.showMessageDialog(null, "por nome");
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where pecas.nome_peca like '%"+jTextFieldNomePeca.getText()+"%'");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }
                
                
           
            }else{
            
                if(Cod != ""){
                
                jButtonPesquisaCliente2ActionPerformed(evt);
            
            
             try {
        JOptionPane.showMessageDialog(null, "por id");
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where pecas.`idPecas` ='"+jTextFieldCodigo.getText()+"'");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }
                
                        
    }
            
}   
            
            
        }else{
            
            
    if(jTextFieldCodigo.getText().equals("") && jComboBoxCategoria.getSelectedItem().equals("-Sel-")
                && jTextFieldEstoque_Inicial.getText().equals("") && jTextFieldEstoque_Final.getText().equals("") &&
            (Produto != "") && (jFormattedTextFieldData_Validade_inicial.getText().equals("  -  -    "))
            && (jFormattedTextFieldData_Validade_Final.getText().equals("  -  -    ")) ){
    
        //Por nome
              try {
        JOptionPane.showMessageDialog(null, "por nome baixo");
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where pecas.nome_peca like '%"+jTextFieldNomePeca.getText()+"%'");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }
        
        }else{
            
    //Por categoria    
    if(jTextFieldCodigo.getText().equals("") && (Categoria != "")
                && jTextFieldEstoque_Inicial.getText().equals("") && jTextFieldEstoque_Final.getText().equals("") &&
            jTextFieldNomePeca.getText().equals("")    && (jFormattedTextFieldData_Validade_inicial.getText().equals("  -  -    "))
            && (jFormattedTextFieldData_Validade_Final.getText().equals("  -  -    "))){
                
                JOptionPane.showMessageDialog(null, "Categoria");
            
                try {
        
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where pecas.aplicacao ='"+jComboBoxCategoria.getSelectedItem()+"'");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }
                
                
            }else{
                
        if (jTextFieldCodigo.getText().equals("") && (jComboBoxCategoria.getSelectedItem().equals("-Sel-"))
                && (Estoque_Inicial_String != "") && (Estoque_Final_String != "") &&
            jTextFieldNomePeca.getText().equals("")    && (jFormattedTextFieldData_Validade_inicial.getText().equals("  -  -    "))
            && (jFormattedTextFieldData_Validade_Final.getText().equals("  -  -    "))){
      
    try{
    Float Estoque_Inicial = Float.parseFloat(jTextFieldEstoque_Inicial.getText());
    Float Estoque_Final = Float.parseFloat(jTextFieldEstoque_Final.getText());
    
        
    if(Estoque_Inicial >=5 ){

    
        try {
        
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where estoque.`Quant_em_estoque` >='"+Estoque_Inicial+"' and estoque.`Quant_em_estoque` <='"+Estoque_Final+"'");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }

    }
   
    }catch (NumberFormatException ex2){
        
        JOptionPane.showMessageDialog(null, "Valor Não é Válido!"); 
    
    }
  
    
        }else{
            
            
    if(jTextFieldCodigo.getText().equals("") && jComboBoxCategoria.getSelectedItem().equals("-Sel-")
                && jTextFieldEstoque_Inicial.getText().equals("") && jTextFieldEstoque_Final.getText().equals("") &&
            jTextFieldNomePeca.getText().equals("") && (Data_Inicial_String != "  -  -    ")
            && (Data_Final_String != "  -  -    ")){
     
        
        JOptionPane.showMessageDialog(null, "Por Data");

                      try {        
        //Data Validade Inicial
        String diava = jFormattedTextFieldData_Validade_inicial.getText().substring(0,2);
        String mesva = jFormattedTextFieldData_Validade_inicial.getText().substring(3,5);
        String anova = jFormattedTextFieldData_Validade_inicial.getText().substring(6);
        String D_VI = (anova+"-"+mesva+"-"+diava);

        
        //Data Validade Final
        String diavf = jFormattedTextFieldData_Validade_Final.getText().substring(0,2);
        String mesvf = jFormattedTextFieldData_Validade_Final.getText().substring(3,5);
        String anovf = jFormattedTextFieldData_Validade_Final.getText().substring(6);
        String D_VF = (anovf+"-"+mesvf+"-"+diavf);
        
        
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where estoque.data_vencimento >='"+D_VI+"' and estoque.data_vencimento <='"+D_VF+"'");
        
            
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }

                      
            
                 }else{
        //Produto e quantidade em estoque
    
        if (jTextFieldCodigo.getText().equals("") && (Categoria != "-Sel-")
                && (Estoque_Inicial_String != "") && (Estoque_Final_String != "") &&
            jTextFieldNomePeca.getText().equals("")    && (jFormattedTextFieldData_Validade_inicial.getText().equals("  -  -    "))
            && (jFormattedTextFieldData_Validade_Final.getText().equals("  -  -    "))){
      
        
    try{
    Float Estoque_Inicial = Float.parseFloat(jTextFieldEstoque_Inicial.getText());
    Float Estoque_Final = Float.parseFloat(jTextFieldEstoque_Final.getText());
    
        
    if(Estoque_Inicial >=5 ){

    
        try {
        
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where estoque.`Quant_em_estoque` >='"+Estoque_Inicial+"' and estoque.`Quant_em_estoque` <='"+Estoque_Final+"' and pecas.aplicacao ='"+jComboBoxCategoria.getSelectedItem()+"' ");
        
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }

    }
   
    }catch (NumberFormatException ex2){
        
        JOptionPane.showMessageDialog(null, "Valor Não é Válido!"); 
    
    }
        
        
    
    }else{
            //Categoria e data de validade
                if(jTextFieldCodigo.getText().equals("") && (Categoria != "-Sel-")
                && jTextFieldEstoque_Inicial.getText().equals("") && jTextFieldEstoque_Final.getText().equals("") &&
            jTextFieldNomePeca.getText().equals("") && (Data_Inicial_String != "  -  -    ")
            && (Data_Final_String != "  -  -    ")){
                    
                    JOptionPane.showMessageDialog(null, "Categoria e data de validade");
                                  try {        
        //Data Validade Inicial
        String diava = jFormattedTextFieldData_Validade_inicial.getText().substring(0,2);
        String mesva = jFormattedTextFieldData_Validade_inicial.getText().substring(3,5);
        String anova = jFormattedTextFieldData_Validade_inicial.getText().substring(6);
        String D_VI = (anova+"-"+mesva+"-"+diava);

        
        //Data Validade Final
        String diavf = jFormattedTextFieldData_Validade_Final.getText().substring(0,2);
        String mesvf = jFormattedTextFieldData_Validade_Final.getText().substring(3,5);
        String anovf = jFormattedTextFieldData_Validade_Final.getText().substring(6);
        String D_VF = (anovf+"-"+mesvf+"-"+diavf);
        
        
            Conexao.executaSQL("select * from estoque inner join pecas on estoque.`Pecas_idPecas` = pecas.`idPecas` where estoque.data_vencimento >='"+D_VI+"' and estoque.data_vencimento <='"+D_VF+"' and pecas.aplicacao ='"+jComboBoxCategoria.getSelectedItem()+"'");
        
            
            JRResultSetDataSource RelatResult = new JRResultSetDataSource(Conexao.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/"+Tipo_SelecaoRelatorio, new HashMap(), RelatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);
       
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(null, "Erro a Gerar o relatório" +ex);
            
        }

                    
                }
            
        }
    }        
                
            }
            
        }

    }    
        
             }                  
         }
     //}
//}
    
    
     
  
    
        
    }//GEN-LAST:event_jButtonGerar_RelatorioActionPerformed

    private void jComboBoxTipoPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaItemStateChanged
        // TODO add your handling code here:
        
String Combo = (String) jComboBoxTipoPesquisa.getSelectedItem();

        if(Combo =="-Sel-"){
            
//Proteger campos
jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(false);

//Limpar campos
jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();


        }else{

            if (Combo =="ID do Produto"){
                
            //Proteger campos
jTextFieldCodigo.setEnabled(true);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(false);

//Limpar campos
jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();

                
            }else{
                
                if(Combo == "Nome do produto"){
                 
                     //Proteger campos
jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(true);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(false);

//Limpar campos
jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();

                    
                }else{
                    
                    if(Combo == "Data de Validade"){
                        
//Proteger campos
jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(true);
jFormattedTextFieldData_Validade_inicial.setEnabled(true);

jComboBoxCategoria.setEnabled(false);
                        
                        
                    }else{
                        
                        if(Combo == "Quantidade em Estoque"){
                            
                            jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(true);
jTextFieldEstoque_Inicial.setEnabled(true);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(false);
                        
//Limpar campos
jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();


                        }else{
                            
                            if(Combo == "Categoria"){
                           
                                 jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(true);

//Limpar campos
jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();

                                
}else{
                            
                            if(Combo == "Quantidade em Estoque e Categoria"){
                           
                                 jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(true);
jTextFieldEstoque_Inicial.setEnabled(true);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(true);

//Limpar campos
jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();


                            }else{
  
                            if(Combo == "Data de Validade e Categoria"){
                           
                                 jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(true);
jFormattedTextFieldData_Validade_inicial.setEnabled(true);

jComboBoxCategoria.setEnabled(true);
                                
//Limpar campos
jTextFieldCodigo.setText("");
jTextFieldEstoque_Final.setText("");
jTextFieldEstoque_Inicial.setText("");
jTextFieldNomePeca.setText("");

jFormattedTextFieldData_Validade_Final.setText("");
jFormattedTextFieldData_Validade_inicial.setText("");

Preencher_ComboCategoria();


                                    }                                
                                }
                            }
                            
                        }
                        
                    }
                    
                    
                    
                    
                }
                
            }

        }
      
        
    
    }//GEN-LAST:event_jComboBoxTipoPesquisaItemStateChanged

    private void jComboBoxTipoPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMouseClicked

    private void jComboBoxTipoPesquisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMouseEntered
        // TODO add your handling code here:
        
        if(jComboBoxTipoPesquisa.getSelectedItem().equals("-Sel-")){
            
//Proteger campos
jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(false);


        }else{

            if(jComboBoxTipoPesquisa.getSelectedItem().equals("ID do Produto")){
                
            //Proteger campos
jTextFieldCodigo.setEnabled(true);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(false);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(false);

                
            }else{
                
                if(jComboBoxTipoPesquisa.getSelectedItem().equals("Nome do produto")){
                 
                     //Proteger campos
jTextFieldCodigo.setEnabled(false);
jTextFieldEstoque_Final.setEnabled(false);
jTextFieldEstoque_Inicial.setEnabled(false);
jTextFieldNomePeca.setEnabled(true);

jFormattedTextFieldData_Validade_Final.setEnabled(false);
jFormattedTextFieldData_Validade_inicial.setEnabled(false);

jComboBoxCategoria.setEnabled(false);

                    
                }
                
            }

        }

        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMouseEntered

    private void jComboBoxTipoPesquisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMouseExited
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMouseExited

    private void jComboBoxTipoPesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMousePressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMousePressed

    private void jComboBoxTipoPesquisaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMouseReleased

    private void jComboBoxTipoPesquisaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMouseDragged

    private void jComboBoxTipoPesquisaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMouseMoved

    private void jComboBoxTipoPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaFocusGained
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jComboBoxTipoPesquisaFocusGained

    private void jComboBoxTipoPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaFocusLost

    private void jComboBoxTipoPesquisaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaPropertyChange
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_jComboBoxTipoPesquisaPropertyChange

    private void jComboBoxTipoPesquisaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBoxTipoPesquisaVetoableChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaVetoableChange

    private void jComboBoxTipoPesquisaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaMouseWheelMoved
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBoxTipoPesquisaMouseWheelMoved

    private void jComboBoxTipoPesquisaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaCaretPositionChanged
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_jComboBoxTipoPesquisaCaretPositionChanged

    private void jComboBoxTipo_relatorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipo_relatorioItemStateChanged
        // TODO add your handling code here:
        
        String Tipo_Relatorio = (String) jComboBoxTipo_relatorio.getSelectedItem();
        
        if(Tipo_Relatorio == "Analítico"){
            
            Tipo_SelecaoRelatorio = "RelatorioEstoque.jasper";
       
        }else
            if(Tipo_Relatorio == "Resumo Geral"){
                
                Tipo_SelecaoRelatorio = "RelatorioEstoqueGeral.jasper";
            
                            
            }
        
        
    }//GEN-LAST:event_jComboBoxTipo_relatorioItemStateChanged
    
 
    
       public class Frm_ProdutoPesquisa extends javax.swing.JFrame {

    Conecta_Banco Conexao = new Conecta_Banco();
    
    SCadastro_PecasVO ModPecas = new SCadastro_PecasVO();
    
//    JI_VendaPecas Cliente = new JI_VendaPecas();
   
    String Nome_Clientem;
    
    int Código_Produto;
    
    /**
     * Creates new form Frm_PesquisaCliente
     */
    public Frm_ProdutoPesquisa() {
        initComponents();
        //Frm_Cliente Cliente_Nome = new Frm_Cliente();
        
        //PreencherTabela_PesquisaCliente("select * from cadastro_cliente where nome_cliente like '%"+ModCliente.getNome_PesquisaTabela()+"%'");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesquisaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Clientes");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 350));

        jTablePesquisaClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePesquisaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePesquisaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jTablePesquisaClientesMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        // TODO add your handling code here:

        
        Valores_TabelaPesquisa();
    
        jTextFieldCodigo.setText(String.valueOf(ModPecas.getId_pecas()));
               
       
        jButtonPesquisaCliente2ActionPerformed(null);
        
    }                                                 

    
    
  
    
    public void PreencherTabela_PesquisaProduto (String sql){
        
        Conexao.conexao();
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Código", "Nome", ""};
    
    
    Conexao.executaSQL(sql);
    
        try {
            Conexao.rs.first();
            
            do{
                dados.add(new Object [] {Conexao.rs.getString("idPecas"),Conexao.rs.getString("nome_peca"), Conexao.rs.getString("fabricante_pecas_idfabricante_pecas")});
            }while (Conexao.rs.next()); 
                          
            } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Erro no preenchimento do Array List "+ex);
        }
                
        ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        
        jTablePesquisaClientes.setModel(modelo);
        
        jTablePesquisaClientes.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTablePesquisaClientes.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisaClientes.getColumnModel().getColumn(1).setPreferredWidth(320);
        jTablePesquisaClientes.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisaClientes.getColumnModel().getColumn(2).setPreferredWidth(155);
        jTablePesquisaClientes.getColumnModel().getColumn(2).setResizable(false);
        
        jTablePesquisaClientes.setAutoResizeMode(jTablePesquisaClientes.AUTO_RESIZE_OFF);
        jTablePesquisaClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Conexao.desconecta();
    
        
    }  
    
  
    
    public void Valores_TabelaPesquisa (){
          
          int Cod_Produto;         
          int Selecao = jTablePesquisaClientes.getSelectedRow();
          Cod_Produto = Integer.parseInt(jTablePesquisaClientes.getModel().getValueAt(Selecao,0).toString());
         // jTextFieldplaca.setText(jTabletabelaItensVenda.getModel().getValueAt(Selecao, ));
          ModPecas.setId_pecas(Cod_Produto);
     
        JOptionPane.showMessageDialog(null, ModPecas.getId_pecas());
          
    }
                 
  // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePesquisaClientes;
    // End of variables declaration                   
}    
              

    public void Recebendo2 (String recebe){
        jLabelUser.setText(recebe);
    }
    
    public void PreencherCombo_TipoRelatorio (){
        
        jComboBoxTipo_relatorio.removeAllItems();
        
        jComboBoxTipo_relatorio.addItem("Resumo Geral");
        jComboBoxTipo_relatorio.addItem("Analítico");
        
        
    }


                public void Preencher_ComboCategoria (){
                
             jComboBoxCategoria.removeAllItems();
             jComboBoxCategoria.addItem("-Sel-");
                
             jComboBoxCategoria.addItem("Cereais");
             jComboBoxCategoria.addItem("Frutas");
             jComboBoxCategoria.addItem("Verduras");
            }

                public void Preencher_ComboTipoPesquisa (){
                
             jComboBoxTipoPesquisa.removeAllItems();
             jComboBoxTipoPesquisa.addItem("-Sel-");
                
             jComboBoxTipoPesquisa.addItem("ID do Produto");
             jComboBoxTipoPesquisa.addItem("Nome do produto");
             jComboBoxTipoPesquisa.addItem("Data de Validade");
             jComboBoxTipoPesquisa.addItem("Quantidade em Estoque");
             jComboBoxTipoPesquisa.addItem("Categoria");
             jComboBoxTipoPesquisa.addItem("Quantidade em Estoque e Categoria");
             jComboBoxTipoPesquisa.addItem("Data de Validade e Categoria");
             
            }
                
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtualizar_Registro;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGerar_Relatorio;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonModoPesquisa;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisaCliente1;
    private javax.swing.JButton jButtonPesquisaCliente2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxTipoPesquisa;
    private javax.swing.JComboBox<String> jComboBoxTipo_relatorio;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_Validade_Final;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_Validade_inicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEstoque_Final;
    private javax.swing.JTextField jTextFieldEstoque_Inicial;
    private javax.swing.JTextField jTextFieldNomePeca;
    // End of variables declaration//GEN-END:variables
}
